OpenVisualCloud/Media-Transport-Library

- include/st20_dpdk_api.h
- lib/src/st_main.h
- lib/src/st_rx_video_session.c
- lib/src/st_tx_video_session.c
- tests/src/st20_test.cpp
- tests/src/tests.h
st20 frame only support positive stride, the linesize should be wider than the original width size.
Linesize can only be used with single line packing mode now, for other packing has packet payload from 2 lines which is not continuous memory.
> st20: add linesize(stride) support

- CHANGELOG.md
- app/src/tx_video_app.c
- include/st20_dpdk_api.h
- include/st20_redundant_api.h
- include/st_dpdk_api.h
- include/st_pipeline_api.h
- lib/src/pipeline/st20_pipeline_rx.c
- lib/src/pipeline/st20_pipeline_tx.c
- lib/src/pipeline/st22_pipeline_rx.c
- lib/src/pipeline/st22_pipeline_tx.c
- lib/src/redundant/st20_redundant_rx.c
- lib/src/st_main.h
- lib/src/st_rx_video_session.c
- lib/src/st_tx_video_session.c
- lib/src/st_util.c
- lib/src/st_util.h
- tests/src/st20p_test.cpp
- tests/src/st22p_test.cpp
- tests/src/tests.h
notify_vsync callback which happened when epoch time change to a new frame, vsync period is same to fps.
> video: add notify_vsync callback support.

- CHANGELOG.md
- app/src/app_base.h
- app/src/args.c
- app/src/rxtx_app.c
- doc/run.md
- include/st_dpdk_api.h
- include/st_pipeline_api.h
- lib/src/pipeline/st20_pipeline_rx.c
- lib/src/pipeline/st20_pipeline_tx.c
- lib/src/st_dev.c
- lib/src/st_main.c
- lib/src/st_main.h
- lib/src/st_platform.h
- lib/src/st_rx_video_session.c
- lib/src/st_sch.c
- lib/src/st_sch.h
- lib/src/st_tx_video_session.c
- tests/src/st20p_test.cpp
1. each tasklet can set the expected sleep interval(us).
2. use timer if the tasklet sleep time > threshold(200us), use timer.
3. app can control if sch can enable sleep or not, by st_sch_enable_sleep
> tasklet: add timer option for sleep

- app/src/parse_json.c
- app/tools/convert_app.c
- app/tools/convert_app_args.c
- app/tools/convert_app_base.h
- include/st20_dpdk_api.h
- include/st_convert_api.h
- include/st_convert_internal.h
- include/st_pipeline_api.h
- lib/src/pipeline/st20_pipeline_rx.c
- lib/src/pipeline/st20_pipeline_tx.c
- lib/src/st_fmt.c
- tests/src/cvt_test.cpp
This PR adds support for 4:2:2 12 bits format in the convert app and st20 pipeline.
If you find this PR satisfactory, I will proceed to add YCbCr 4:4:4 and RGB 10/12 bits in the same way.
> Added support for 4:2:2 12 bits format

- app/src/parse_json.c
- app/tools/convert_app.c
- app/tools/convert_app_args.c
- app/tools/convert_app_base.h
- include/st20_dpdk_api.h
- include/st_convert_api.h
- include/st_convert_internal.h
- include/st_pipeline_api.h
- lib/src/pipeline/st20_pipeline_rx.c
- lib/src/pipeline/st20_pipeline_tx.c
- lib/src/st_fmt.c
- tests/src/cvt_test.cpp
This adds support for YCbCr 4:4:4 12 bits and RGB 4:4:4 12 bits.
I will look at updating the documentation for the new formats next.
> Added support for 4:4:4 12 bits formats

- app/sample/rx_st20_tx_st20_split_fwd.c
../../app/sample/rx_st20_tx_st20_split_fwd.c:190:7: error: ‘fi’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> build: fix uninitialized error in ubuntu 22.04 build

- include/st_pipeline_api.h
- lib/src/pipeline/st20_pipeline_rx.c
- lib/src/pipeline/st20_pipeline_tx.c
- tests/src/st20p_test.cpp
- tests/src/tests.h
This function is only used for internal convert mode and the ST20P_RX_FLAG_EXT_FRAME flag should be set, the convert is done in this call.
> st20p/rx: add get_ext_frame api

- .github/workflows/ubuntu_build_with_gtest.yml
add a fallback value for concurrency
refer to https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
> ci: fix gtest workflow for push

- .github/workflows/ubuntu_build.yml
- build.sh
- lib/src/mt_arp.c
- lib/src/mt_cni.c
- lib/src/mt_dev.c
- lib/src/mt_dev.h
- lib/src/mt_kni.c
- lib/src/mt_log.h
- lib/src/mt_main.h
- lib/src/mt_mcast.c
- lib/src/mt_ptp.c
- lib/src/mt_sch.c
- lib/src/mt_tap.c
- lib/src/mt_util.c
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_video_session.c
Reduce tx queue usage since some device only has 2 or 4 queues.
> tx/queue: arp/mcast/ptp use one shared tx queue.

- .github/workflows/ubuntu_build.yml
- app/sample/rx_st22_pipeline_sample.c
- app/sample/sample_util.c
- app/sample/sample_util.h
- app/sample/tx_st22_pipeline_sample.c
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/pipeline/st20_pipeline_tx.c
- lib/src/st2110/pipeline/st22_pipeline_rx.c
- lib/src/st2110/pipeline/st22_pipeline_tx.c
- lib/src/st2110/st_fmt.c
- lib/src/st2110/st_fmt.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_tx_video_session.c
- plugins/st22_ffmpeg/README.md
- plugins/st22_ffmpeg/meson.build
- plugins/st22_ffmpeg/st22_ffmpeg_plugin.c
- plugins/st22_ffmpeg/st22_ffmpeg_plugin.h
- tests/src/st22p_test.cpp
./build/app/TxSt22PipelineSample --st22_codec h264_cbr --st22_fmt YUV422PLANAR8 --tx_url test_planar8.yuv
./build/app/RxSt22PipelineSample --st22_codec h264_cbr --st22_fmt YUV422PLANAR8 --rx_url out_planar8.yuv
> plugin/st22: fix st22_ffmpeg on new frame API.

- lib/src/mt_arp.c
- lib/src/mt_cni.c
- lib/src/mt_dev.c
- lib/src/mt_dev.h
- lib/src/mt_main.h
- lib/src/mt_ptp.c
- lib/src/st2110/st_ancillary_transmitter.c
- lib/src/st2110/st_audio_transmitter.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_video_session.c
- lib/src/st2110/st_video_transmitter.c
queue user should not direct use the queue id and tx/rx burst function.
> dev/queue: use queue info handle for get/put api

- lib/src/mt_arp.c
- lib/src/mt_arp.h
- lib/src/mt_main.h
- lib/src/mt_mcast.c
mcast: move mt_mcast_impl to per port struct
arp: move mt_arp_impl to per port struct
use lock to protect the entries
> arp: add reentrant support

- lib/src/st2110/st_rx_video_session.c
pcapng may has value when pcapng_max_pkts is not updated.
> rx/video: fix St22_rx.pcap_dump fail randomly

- app/udp/udp_server_sample.c
[2022-12-14T11:37:43.019Z] ../../app/udp/udp_server_sample.c:5:10: fatal error: poll.h: No such file or directory
[2022-12-14T11:37:43.019Z]  #include <poll.h>
> build: fix win build

- lib/src/mt_main.c
- lib/src/mt_mem.h
- lib/src/mt_stat.c
- lib/src/mt_util.c
- tests/src/st30_test.cpp
for example:
MT: mt_asan_check, leak of 128 byte(s) at 0x7f1f2d62c500
MT: mt_asan_check, backtrace info:
MT: mt_asan_check, /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7f43d78dcc0e]
MT: mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(mt_rte_zmalloc_socket+0x18d) [0x7f43d755cc91]
MT: mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(mt_sch_register_tasklet+0x112) [0x7f43d74e912a]
MT: mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(st_video_transmitter_init+0x2e2) [0x7f43d7616bb4]
MT: mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(st_tx_video_sessions_sch_init+0x12d) [0x7f43d76041f6]
MT: mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(+0x140641) [0x7f43d757b641]
MT: mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(+0x1412a2) …
> asan: print backtrace info of rte_malloc leaks

- app/src/app_platform.h
declare nfds_t for windows.
typedef unsigned long int nfds_t;
> build: fix windows build with nfds_t

- lib/src/mt_dev.c
- lib/src/mt_main.h
Always get below log if app are running from multi thread with vf.
_atomic_set_cmd(): There is incomplete cmd 112
iavf_fdir_add(): fail to execute command OP_ADD_FDIR_FILTER
iavf_flow_create(): Failed to create flow
> lib/dev: add lock for vf command

- app/sample/sample_util.c
- app/sample/sample_util.h
- app/src/args.c
- app/udp/udp_client_sample.c
- app/udp/udp_server_sample.c
- app/udp/ufd_client_sample.c
- app/udp/ufd_server_sample.c
- include/mudp_api.h
- include/mudp_sockfd_api.h
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_video_session.c
- lib/src/udp/udp_main.c
- lib/src/udp/udp_main.h
- lib/src/udp/ufd_main.c
use mudp_set_tx_mac/mufd_set_tx_mac
udp test:
./build/app/UdpClientSample --p_tx_dst_mac 42:c7:17:08:92:29 ./build/app/UdpServerSample --p_tx_dst_mac 0e:48:fa:3d:55:83
ufd test:
MUFD_CFG=app/udp/ufd_client.json ./build/app/UfdClientSample --p_tx_dst_mac 42:c7:17:08:92:29
MUFD_CFG=app/udp/ufd_server.json ./build/app/UfdServerSample --p_tx_dst_mac 0e:48:fa:3d:55:83
> udp: support mac address by user

- lib/src/mt_dev.c
all control path of afxdp should use kernel socket path
fixes 5097e7969eed74080472381f394b004ea8cc024a
> afxdp: no system tx queue

- CHANGELOG.md
- app/sample/sample_util.c
- include/mtl_api.h
- lib/src/mt_arp.c
- lib/src/mt_dev.c
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/mt_socket.c
- lib/src/mt_socket.h
- lib/src/mt_util.h
- tests/src/tests.cpp
An address has both ip and netmask, netmask can be used to decide if a IP is lan or wan. Later we will add a hook way to get mac for wan.
> api: add netmask support

- app/meson.build
- app/perf/meson.build
- app/perf/perf_test.sh
- app/perf/rfc4175_422be12_to_le.c
- app/sample/sample_util.c
- app/sample/sample_util.h
- doc/convert.md
- include/st_convert_api.h
- include/st_convert_internal.h
- lib/src/st2110/st_avx512.c
- lib/src/st2110/st_avx512.h
- lib/src/st2110/st_convert.c
- tests/src/cvt_test.cpp
scalar, time: 0.051987 secs with 60 frames(640x480,0.878906m@3 buffers)
avx512, time: 0.006813 secs with 60 frames(640x480@3 buffers)
avx512, 7.630559x performance to scalar
dma+avx512, time: 0.009418 secs with 60 frames(640x480@3 buffers)
dma+avx512, 5.519962x performance to scalar
scalar, time: 0.102720 secs with 60 frames(1280x720,2.636719m@3 buffers)
avx512, time: 0.019190 secs with 60 frames(1280x720@3 buffers)
avx512, 5.352788x performance to scalar
dma+avx512, time: 0.032228 secs with 60 frames(1280x720@3 buffers)
dma+avx512, 3.187290x performance to scalar
scalar, time: 0.212847 secs with 60 frames(1920x1080,5.932617m@3 buffers)
avx512, time: 0.035059 secs with 60 frames(1920x1080@3 buffers)
avx512, 6.071108x performance to scalar
dma+avx512, time: 0.051582 secs with 60 …
> cvt: add rfc4175 422be12 to le avx512 version

- include/meson.build
- include/mudp_sockfd_internal.h
- lib/src/udp/ufd_main.c
- lib/src/udp/ufd_main.h
To support the incoming gtest routine which not use json cfg. That test can be easily deployed.
> ufd: add internal api.

- app/sample/sample_util.c
- app/src/args.c
- doc/run.md
- include/mtl_api.h
- lib/src/mt_dev.c
- lib/src/mt_dev.h
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/mt_ptp.c
To debug issue which user ptp source is not stable, use --ptp_tsc to enable.
> ptp: add tsc as ptp source for debug usage.

- lib/src/mt_arp.c
- lib/src/mt_main.h
- lib/src/mt_mcast.c
- lib/src/mt_ptp.c
- lib/src/mt_ptp.h
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
reduce memory usage since MTL_PORT_MAX is extent to 8 now
> arp/mcast/ptp: malloc context at runtime

- .github/workflows/ubuntu_build_with_gtest.yml
- doc/dma.md
- ecosystem/librist/build_librist_mtl.sh
- include/mtl_api.h
- lib/src/mt_dev.c
- lib/src/mt_main.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_video_session.c
- tests/src/tests.cpp
The best setup: IOMMU enabled, DPDK in IOVA VA mode, 2MB hugepages enabled.
The second choice: IOMMU not supported, enable no_iommu for vfio driver, DPDK in IOVA PA mode, 2MB hugepages enabled.
The third option(will be deprecated): IOMMU not supported, enable no_iommu for vfio driver, DPDK in IOVA PA mode, 1GB hugepages enabled.
Current windows setup: vfio not supported, use netuio driver, DPDK in IOVA PA mode, 1GB hugepages enabled.
The goal is to abandon 1GB hugepages setting for both Windows and AWS.
Add gtest argument to simulate IOVA PA environment. The test for IOVA PA may take extra long time.
[Notice] Features not supported in IOVA PA mode: st20 ext_frame, st20p ext_frame no convert mode, dma_map/unmap and others.
> st/video: fix dma copy for IOVA PA mode

- app/sample/sample_util.c
- app/udp/udp_test.sh
- build.sh
- include/mudp_sockfd_api.h
- include/mudp_sockfd_internal.h
- ld_preload/meson.build
- ld_preload/meson_options.txt
- ld_preload/preload_platform.h
- ld_preload/udp/meson.build
- ld_preload/udp/udp_preload.c
- ld_preload/udp/udp_preload.h
- lib/src/udp/udp_main.c
- lib/src/udp/ufd_main.c
- script/dos2unix.sh
use LD_PRELOAD to load libmtl_udp_preload.so before libc, that mtl preload take over control the socket API.
Also udp_preload will dlopen libc and dlsym to get the libc socket api function pointer and use it as fallback path.
usage:
MUFD_CFG=app/udp/ufd_client.json
LD_PRELOAD=/usr/local/lib/x86_64-linux-gnu/libmtl_udp_preload.so ./build/app/UsocketClientSample
MUFD_CFG=app/udp/ufd_server.json
LD_PRELOAD=/usr/local/lib/x86_64-linux-gnu/libmtl_udp_preload.so ./build/app/UsocketServerSample
> ld_preload: first version

- include/st20_api.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_video_session.c
Closes #204 
I opted for the disable flag since boxes are not part of st2110-22, but rather part of the underlying RFCs. Since we may encounter other codestream that do not use boxes but still use 2110-22 in the future, it's safer to allow to ignore them.
> Added flags to st22_rx_ops to disable boxes

- ld_preload/udp/udp_preload.c
- ld_preload/udp/udp_preload.h
RTLD_NEXT: Find the next occurrence of the desired symbol in the search order after the current object.
Remove the hardcode use of dlopen.
> upl: use RTLD_NEXT

- doc/build.md
- doc/build_WIN.md
- patches/dpdk/22.11/0009-net-iavf-add-lock-for-VF-commands.patch
fix issue in CI: 
iavf_fdir_del(): Failed to delete rule request due to this rule doesn't exist
iavf_flow_destroy(): Failed to destroy flow
iavf_flow_flush(): Failed to flush flows
> vf: porting net-iavf-add-lock-for-VF-commands patch

- .github/workflows/ubuntu_build_with_gtest.yml
- app/sample/README.md
- app/src/args.c
- include/mtl_api.h
- lib/src/st2110/st_tx_video_session.c
- lib/src/st2110/st_video_transmitter.c
- tests/src/tests.cpp
Currently, reuse tsc way logic but only control the first packet sending time
> st/video: add best effort pacing

- app/meson.build
- app/src/app_base.h
- app/src/meson.build
- app/src/player.c
- app/src/player.h
SDL2 should be an optional dependency.
> app: build support without SDL2

- doc/convert.md
- lib/src/st2110/st_avx512_vbmi.c
- lib/src/st2110/st_avx512_vbmi.h
- lib/src/st2110/st_convert.c
- tests/src/cvt_test.cpp
scalar, time: 0.072550 secs with 60 frames(1280x720,3.515625m@3 buffers)
avx512, time: 0.027209 secs with 60 frames(1280x720@3 buffers)
avx512, 2.666397x performance to scalar
dma+avx512, time: 0.043828 secs with 60 frames(1280x720@3 buffers)
dma+avx512, 1.655334x performance to scalar
avx512_vbmi, time: 0.019603 secs with 60 frames(1280x720@3 buffers)
avx512_vbmi, 3.700964x performance to scalar
dma+avx512_vbmi, time: 0.037665 secs with 60 frames(1280x720@3 buffers)
dma+avx512_vbmi, 1.926191x performance to scalar
scalar, time: 0.163714 secs with 60 frames(1920x1080,7.910156m@3 buffers)
avx512, time: 0.060392 secs with 60 frames(1920x1080@3 buffers)
avx512, 2.710856x performance to scalar
dma+avx512, time: 0.065341 secs with 60 frames(1920x1080@3 buffers)
dma+avx512, 2.505533x …
> cvt: add rfc4175 422be12 to planar vbmi version

- app/sample/tx_st20_pipeline_sample.c
- lib/src/mt_dev.c
- lib/src/mt_dev.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_tx_video_session.c
- tests/src/st20p_test.cpp
- tests/src/tests.h
Trigger the notify_frame_done for last frame to fix issue below:
Some app expect notify_frame_done callback for all TX frames before the destroy process.
> tx/video: add tx done cleanup if no next frame from user

- doc/experimental/header_split.md
- include/mudp_sockfd_internal.h
- ld_preload/udp/udp_preload.c
- ld_preload/udp/udp_preload.h
- lib/src/st2110/st_rx_video_session.c
- lib/src/udp/udp_main.c
- lib/src/udp/udp_main.h
- lib/src/udp/ufd_main.c
query the libc epoll with zero timeout status for each poll.
todo: enable similar for poll and select.
> upl: add mix fd type support for epoll

- ecosystem/ffmpeg_plugin/kahawai_dec.c
In the case of multiple receiver session, the second session will cause a segmentation fault because s->dev_handle is not set.
> ecosystem/ffmpeg_plugin: Fix segmentation fault for multi rx session

- lib/src/mt_platform.h
- lib/src/mt_rss.c
- lib/src/mt_shared_queue.c
- lib/src/mt_stat.c
- lib/src/mt_util.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_video_session.c
- lib/src/udp/udp_main.c
- lib/src/udp/udp_main.h
- lib/src/udp/udp_rxq.c
- lib/src/udp/udp_rxq.h
- lib/src/udp/ufd_main.c
- lib/src/udp/ufd_main.h
prepare for udp stack multi-process support, also memory should use rte_malloc which is shared between process.
> lib/mutex: default enable PTHREAD_PROCESS_SHARED

- script/nicctl.sh
Fix below err when create vf:
Warning: routing table indicates that interface 0000:af:01.0 is active. Not modifying.
> nicctl: add vf down before bind vf to vfio

- ld_preload/preload_platform.h
- ld_preload/udp/udp_preload.c
- ld_preload/udp/udp_preload.h
- lib/src/udp/udp_main.c
- lib/src/udp/udp_rxq.c
- lib/src/udp/udp_rxq.h
- lib/src/udp/ufd_main.c
- lib/src/udp/ufd_main.h
- lib/windows/win_posix.h
Child can not alloc rte memory itself.
> upl: not use rte malloc for child process

- lib/src/st2110/st_rx_video_session.c
The first arriving packet does not need to be no.0 of the frame.
> st/video: allow any first arriving packet

- ld_preload/udp/udp_preload.c
For timeval/timespec type timeout args, use the following rules:
1. NULL: infinite timeout (block indefinitely).
2. Fields are 0: no timeout (return immediately).
3. Others: normal timeout rounded up to the system clock granularity.
For int type timeout args, use the following rules:
1. 0: no timeout (return immediately).
2. Negative value: infinite timeout (block indefinitely).
3. Others: normal timeout rounded up to the system clock granularity.
> udp/preload: fix timeout handling

- app/src/app_base.h
- app/src/parse_json.c
- app/src/parse_json.h
- app/src/rx_ancillary_app.c
- app/src/rx_audio_app.c
- app/src/rx_st20p_app.c
- app/src/rx_st20r_app.c
- app/src/rx_st22p_app.c
- app/src/rx_video_app.c
- app/src/tx_ancillary_app.c
- app/src/tx_audio_app.c
- app/src/tx_st20p_app.c
- app/src/tx_st22p_app.c
- app/src/tx_video_app.c
- include/mtl_api.h
- include/mudp_sockfd_internal.h
- lib/src/mt_cni.c
- lib/src/mt_main.c
- lib/src/udp/ufd_main.c
- tests/script/dhcp_loop_json/1080p59_1v.json
- tests/script/dhcp_loop_json/unicast_1v_1a_1anc.json
- tests/src/tests.cpp
- tests/src/tests.h
- tests/src/ufd_test.cpp
- tests/src/ufd_test.h
Add dhcp_loop_json for app dhcp loop test, use interface idx as the dip/sip, refer to tests/script/dhcp_loop_json/ for usage. Also add --dhcp support for test.
> api: add api to get the ip/address/netmsk for dhcp

- ecosystem/ffmpeg_plugin/kahawai_dec.c
Issue:
On multiple RX sessions, the second RX session initializes after the first packet is received on the first session. Fix:
Return from kahawai_read_packet() if session count doesn't match the active session count.
> Init all rx session before rx packet

- lib/src/meson.build
- lib/src/mt_cni.c
- lib/src/mt_dev.c
- lib/src/mt_dev.h
- lib/src/mt_main.h
- lib/src/mt_ptp.c
- lib/src/mt_queue.c
- lib/src/mt_queue.h
- lib/src/mt_rss.c
- lib/src/mt_rss.h
- lib/src/mt_shared_queue.c
- lib/src/mt_shared_queue.h
- lib/src/mt_shared_rss.c
- lib/src/mt_shared_rss.h
- lib/src/mt_socket.c
- lib/src/mt_socket.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/udp/udp_main.c
- lib/src/udp/udp_rxq.c
- lib/src/udp/udp_rxq.h
mt_rxq_get will call the real rx path according to the system config.
cni/ptp/udp/rx: use mt_rxq_get
> rxq: use mt_rxq_get for all rxq request

- doc/aws.md
- lib/src/mt_dev.c
- lib/src/mt_dev.h
- lib/src/mt_dma.c
- lib/src/mt_dma.h
- lib/src/mt_kni.c
- lib/src/mt_shared_queue.c
- lib/src/mt_tap.c
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_ancillary_session.h
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_audio_session.h
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_rx_video_session.h
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_ancillary_session.h
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_audio_session.h
- lib/src/st2110/st_tx_video_session.c
- lib/src/st2110/st_tx_video_session.h
- lib/src/udp/udp_main.c
- lib/src/udp/udp_main.h
- lib/src/udp/udp_rxq.c
- lib/src/udp/udp_rxq.h
Resolved issue where audio session initialization failed when creating 100 or more sessions. To avoid this problem, the ring and mempool names should be kept concise since the maximum name size is 32.
> lib: use concise name for ring/mempool

- action.yml
Add an option to allow other workflows to integrate IMTL workflow in other repository.
An example, a separate repository which have active FFmpeg development github workflows which build's on top 
Intel Media Transport Library (MTL)
> Add composite action Intel Media Transport Libray

- include/st20_api.h
- include/st20_redundant_api.h
- include/st30_api.h
- include/st40_api.h
- include/st_pipeline_api.h
- lib/src/mt_cni.c
- lib/src/mt_main.h
- lib/src/mt_ptp.c
- lib/src/mt_shared_queue.c
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/pipeline/st22_pipeline_rx.c
- lib/src/st2110/redundant/st20_redundant_rx.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- tests/src/ufd_test.cpp
For one stream, the src port usually is random and no way to get the source port.
> rxq: remove unused src port

- lib/src/mt_util.c
- tests/src/st20_test.cpp
ptp time from sys for cloud instance is not accurate
> vsync: point to next epoch if ptp time is still in current epoch

- app/src/args.c
- include/mtl_api.h
- lib/src/mt_cni.c
- lib/src/mt_cni.h
- lib/src/mt_main.h
- lib/src/mt_queue.c
- lib/src/mt_queue.h
- lib/src/mt_shared_queue.c
- lib/src/mt_tap.c
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
set use_cni_queue to true in mt_rxq_flow to enable it.
For app, use "--rx_use_cni" to enable this debug option.
> queue: add cni base queue support

- .github/workflows/msys2_ffmpeg.yml
Reference example usage on composite action workflow to glue between two workflows which could reside on the same/other github repositories separating IMTL and FFmpeg workflows for clearer definitions.
IMTL Github <action.yml> --> Other Github Repo <workflows.yml> 
IMTL Github <action.yml> --> IMTL Github FFmpeg <workflows.yml>
This workflow action duplicates ecosystem/ffmpeg_plugin/build_ffmpeg_plugin.sh
> Add MSYS2 FFmpeg IMTL plugins composite workflow built support

- doc/run.md
- lib/src/mt_main.h
- lib/src/mt_ptp.c
- tests/src/st20_test.cpp
use tsc time as timesync source if no timesync support.
The accuracy is not stable(max to 10us for VF) since it can't read exactly the t2 and t3 time.
MT: PTP(0): time 1689580576680416367, 2023-07-17 15:55:39
MT: PTP(0): delta avg 3978, min -2313, max 9985, cnt 40
MT: PTP(0): correct_delta avg 442, min -6134, max 6152, cnt 39
MT: PTP(0): path_delay avg 2664, min 2306, max 8591, cnt 39
MT: PTP(0): mode l4, sync cnt 40, expect avg 4483:667@0.251065s
MT: PTP(0): rx time error 0, tx time error 0, delta result error 1
MT: PTP(0): time 1689580596680572512, 2023-07-17 15:55:59
MT: PTP(0): delta avg 3853, min 3568, max 4130, cnt 40
MT: PTP(0): correct_delta avg 116, min -269, max 368, cnt 40
MT: PTP(0): path_delay avg 2497, min 2341, max 2756, cnt 40
MT: PTP(0): mode l4, sync cnt 40, expect avg …
> ptp: add no timesync support

- app/src/app_base.h
- app/src/rx_audio_app.c
- app/src/tx_audio_app.c
- include/st30_api.h
- lib/src/st2110/st_fmt.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_tx_audio_session.c
- tests/script/loop_json/unicast_4a.json
- tests/src/st30_test.cpp
It's duplicate to fmt, channel, ptime, sampling
> audio: deprecate sample_size and sample_num

- lib/src/mt_main.h
- lib/src/mt_sch.c
- lib/src/mt_shared_queue.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_video_session.c
audio_transmitter avg time reduce to 30us from 96us for tx_shared_queue_750v.json
stat: add time info for frame get/notify call back
> tsq: use spin lock to protect the tx burst

- CHANGELOG.md
- app/src/app_base.h
- app/src/app_platform.h
- app/src/args.c
- app/src/parse_json.c
- app/src/parse_json.h
- app/src/rxtx_app.c
- doc/configuration_guide.md
- doc/run.md
- include/mtl_api.h
- lib/src/mt_main.c
- lib/src/st2110/st_rx_video_session.c
Ex, use "--log_file test.log" argument to output the log instead of console.
> log: add log to file support by mtl_openlog_stream

- app/src/parse_json.c
- lib/src/st2110/st_tx_video_session.c
get second field from rtp buffer
> st20: fix half fps issue for interlace rtp mode

- app/src/parse_json.c
- lib/src/st2110/st_tx_video_session.c
get second field from rtp buffer
(cherry picked from commit 94a550df904d95f2a1d8135bb15f73e76b705233)
> st20: fix half fps issue for interlace rtp mode (#388)

- lib/src/st2110/st_tx_video_session.c
- tests/src/st20_test.cpp
test: check meta_timing only if fps check is true
test: no fps check for detect_uframe_mix_s2
tx/video: fix user_meta ipv4 hdr
(cherry picked from commit d0847f2b52807d4464aac2c2a681e3b54d933d37)
> test: fix the test on aws

- lib/src/mt_dev.c
- lib/src/mt_shared_queue.c
- tests/src/st20_test.cpp
use double to make sure all the fifo are burst out to clean all mbufs in the pool
> queue/tx: double burst pkts for tx queue flush

- lib/src/mt_dev.c
- lib/src/mt_shared_queue.c
- tests/src/st20_test.cpp
use double to make sure all the fifo are burst out to clean all mbufs in the pool
(cherry picked from commit c7305d962c0321e3a4cd97049aaa71c47532a937)
> queue/tx: double burst pkts for tx queue flush (#398)

- app/src/rx_video_app.c
- include/st20_api.h
- lib/src/mt_rtcp.c
- lib/src/mt_rtcp.h
- lib/src/mt_util.c
- lib/src/mt_util.h
- lib/src/st2110/st_rx_video_session.c
- tests/src/st20_test.cpp
- tests/src/st22_test.cpp
1. use bitmap for loss detection, default window size is 16*8
2. add skip window to handle some out of order cases
3. calculate num_fci before alloc mbuf
4. remove the nack item and its expire timer
> rtcp/rx: use bitmap and window to detect loss

- app/src/rxtx_app.c
- app/src/tx_st20p_app.c
- app/src/tx_video_app.c
- include/st20_api.h
- include/st_api.h
- lib/src/mt_dev.c
- lib/src/mt_dev.h
- lib/src/mt_main.h
- lib/src/mt_queue.c
- lib/src/mt_queue.h
- lib/src/mt_shared_queue.c
- lib/src/mt_shared_queue.h
- lib/src/mt_util.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_tx_video_session.c
- lib/src/st2110/st_video_transmitter.c
- lib/src/st2110/st_video_transmitter.h
- tests/script/loop_json/st20p_redundant_1v_1080p59.json
- tests/script/loop_json/st20p_redundant_1v_v210.json
tx burst may hang on one queue due to malicious event on VF, we add hang check by poll the tx burst status, and use another queue to continue the frame sending.
And application should malloc more queues to allow lib can alloc a new queue in failed case.
For simulated test, please set MT_DEV_SIMULATE_MALICIOUS_PKT to 1.
> tx/video: add recovery from tx burst hang

- lib/src/st2110/st_rx_video_session.c
In some case when the marker packet lost, the retransmission happens after next frame packet arrives, so there should be at least 2 frame slots.
If the marker packet is missed and not recovered, frame notify latency can be at lease 1 frame time.
> rx/video: use 2 frame slots when rtcp enabled

- ecosystem/ffmpeg_plugin/kahawai_common.c
- ecosystem/ffmpeg_plugin/kahawai_common.h
- ecosystem/ffmpeg_plugin/kahawai_dec.c
- ecosystem/ffmpeg_plugin/kahawai_enc.c
1) libavdevice/kahawai_common.h:33:1: warning: function declaration isn't a prototype [-Wstrict-prototypes] mtl_handle kahawai_get_handle();
2) libavdevice/kahawai_common.c:54:5: warning: 'tx_sessions_cnt_max' is deprecated: Use tx_queues_cnt instead [-Wdeprecated-declarations] 
3) libavdevice/kahawai_common.c:58:5: warning: 'rx_sessions_cnt_max' is deprecated: Use rx_queues_cnt instead [-Wdeprecated-declarations] 
4) warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement] 
5) warning: '__builtin_strncpy' specified bound 64 equals destination size [-Wstringop-truncation]
> Resolved warnings introduced

- lib/src/mt_dev.c
- lib/src/mt_main.h
- script/nicctl.sh
The pull request makes changes in the nicctl.sh script to identify if the mlx driver is loaded.
If so then the NVIDIA PMD which uses bifurcated driver is in play.
As a result do not bind the vfio-pci to the created VFs.
Also added a new support for mlx5_pci driver in the library.
> Added support for mellanox ConnectX cards. Nvidia PMD uses bifurcated driver don't bind vfio-pci to VFs

- ecosystem/ffmpeg_plugin/README.md
The udp_port of the RxTxApp will increment by two when operating in replica mode.
(cherry picked from commit 701404aff233d3889d477f4515f62327514e93ca)
> ecosystem/ffmpeg: doc for udp_port increment by 2 (#420)

- app/src/app_base.h
- app/src/args.c
- app/src/tx_st20p_app.c
- app/src/tx_video_app.c
- doc/run.md
- include/st20_api.h
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_tx.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_tx_video_session.c
A synthetic source can timestamp at the start of the frame or at the
time the first packet egresses from the sender. App can customize
this by rtp_timestamp_delta_us.
> tx/video: add rtp timestamp delta support.

- lib/src/mt_main.h
- lib/src/mt_util.c
- tests/src/st20_test.cpp
- tests/src/test_util.cpp
When packets at the end of frame lost, the time to receive the whole frame will be longer.
> test: ignore timing check when rtcp enabled

- lib/src/mt_rtcp.c
- lib/src/mt_rtcp.h
rtcp_tx_free may hang because enqueue not stopped while cleaning the mbuf ring.
> rtcp: add active control

- lib/src/mt_dev.c
open an existing file with O_CREAT can fail
> dev: try again to open lock file (#445)

- lib/src/mt_rtcp.c
fix dead loop when last_seq is UINT16_MAX
> rtcp/rx: fix compare with last_seq

- lib/src/mt_platform.h
Keep attr in scope to prevent usage of dangling pointer
> Fix dangling pointer in mt_platform.h

- .github/workflows/windows_build_with_gtest.yml
- app/udp/udp_client_sample.c
- app/udp/udp_server_sample.c
- include/mtl_api.h
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/udp/ufd_main.c
UDP and ST2110 can co-exist, and actually no code are using this field.
> api: remove transport type from mtl_init

- app/src/args.c
- app/src/rxtx_app.c
- include/mtl_api.h
- lib/src/mt_dev.c
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/mt_socket.c
- lib/src/mt_socket.h
- lib/src/mt_util.c
- lib/src/mt_util.h
- lib/src/st2110/st_fmt.c
- tests/script/afxdp_json/1080p59_1v.json
- tests/script/afxdp_json/mix_port.json
- tests/script/afxdp_json/mix_port2.json
- tests/script/afxdp_json/multicast_1v_1a_1anc.json
- tests/script/afxdp_json/multicast_redundant_1v_1a_1anc.json
- tests/script/afxdp_json/rtp_1080p59_1v.json
- tests/script/afxdp_json/rtp_multicast_1v_1a_1anc.json
- tests/script/afxdp_json/rtp_redundant_1v_1a_1anc.json
- tests/script/afxdp_json/ufd_client.json
- tests/script/afxdp_json/ufd_server.json
- tests/script/afxdp_json/unicast_1080p59_1v.json
to support other future kernel based PMD.
> afxdp: port name use prefix "afxdp:"

- .github/workflows/msys2_build.yml
- meson.build
The cached DPDK binaries are retrieved but not used to reduce MSYS2 CI time. Add '--no-rebuild' to fix it.
> ci: do not rebuild dpdk for msys2

- app/sample/ext_frame/rx_st20_pipeline_dyn_ext_frame_sample.c
- doc/external_frame.md
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/pipeline/st20_pipeline_rx.h
- tests/src/st20p_test.cpp
- tests/src/tests.h
Simply the usage, for non-converter use raw st20 dynamic ext mode, for convert, call the ext frame query in the frame ready callback.
> st20/rx: use dynamic ext frame for both converter and non-converter mode

- app/sample/sample_util.c
To enable the built-in ptp for sample app.
> sample: add "--ptp" args

- ecosystem/ffmpeg_plugin/kahawai_common.c
- include/mtl_api.h
- lib/src/mt_socket.c
test with: 
ffmpeg -framerate 60 -pixel_format yuv422p10le -width 1920 -height 1080 -udp_port 20000 -port kernel:enp175s0f0np0 -src_addr "239.168.85.20" -ext_frames_mode 1 -f kahawai -i "k" -vframes 2000 -f rawvideo /dev/null -y
> ecosystem/ffmpeg_plugin: add pmd type support

- app/meson.build
- app/sample/dma/dma_sample.c
- app/src/app_base.h
- app/src/app_platform.h
- app/src/args.c
- app/src/rx_st20p_app.c
- app/src/rx_video_app.c
- app/src/rxtx_app.c
- app/src/tx_st20p_app.c
- app/src/tx_video_app.c
Enabled by "--video_sha_check", the sha digest is carried by the user meta
> app: add video check sha option

- app/src/app_platform.h
- lib/src/mt_ptp.c
- lib/windows/win_posix.c
- lib/windows/win_posix.h
Adjusting frequency is not stable on Windows for now.
> ptp: add limited phc2sys for windows

- lib/src/mt_main.c
MT: Error: mt_dev_get_socket_id, failed to get port for 0000:af:00.0
MT: Error: mt_dev_get_socket_id, please make sure the driver of 0000:af:00.0 is configured rightly
MT: Error: mtl_init, get socket fail -19 for pmd 0
MT: Error: mtl_init, run "dpdk-devbind.py -s | grep Ethernet" to check if other port driver is ready as vfio-pci mode
> doc: add dpdk-devbind.py hint if the port is not set to vfio-pci

- lib/src/mt_ptp.c
- lib/src/mt_rtcp.c
- lib/src/mt_rtcp.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_video_session.c
- lib/src/udp/udp_main.c
- lib/src/udp/udp_main.h
The packet id is set to 0 when IP_DF flag set,
which is identical to the kernel behavior.
> lib: fix the use of ipv4 packet id

- lib/src/datapath/mt_queue.c
- lib/src/dev/mt_af_xdp.c
- lib/src/dev/mt_dev.c
test with:
sudo ./build/app/RxTxApp --config_file tests/script/native_af_xdp_json/loop.json --video_sha_check
> dp/xdp: add MT_IF_FEATURE_TX_MULTI_SEGS support

- lib/src/dev/mt_af_xdp.c
- tests/script/native_af_xdp_json/loop.json
Other type packet may be dispatched to the flow queue also.
> dp/xdp: add pkt header check for rx

- app/src/rxtx_app.c
- doc/run.md
- include/mtl_api.h
- lib/src/dev/mt_af_xdp.c
- lib/src/dev/mt_dev.c
- lib/src/mt_ptp.c
Some operations require specific capabilities to run, if the app is not run under root user, the caps should be added.
> lib: add hints for capabilities

- lib/src/datapath/mt_queue.c
- lib/src/datapath/mt_shared_queue.c
- lib/src/datapath/mt_shared_rss.c
- lib/src/dev/mt_af_xdp.c
- lib/src/dev/mt_af_xdp.h
- lib/src/dev/mt_dev.c
- lib/src/mt_main.h
- tests/script/native_af_xdp_json/rss.json
To use rss on XDP, please make sure the combined queue count is less than the CPU cores.
test with:
sudo ethtool -L enp0s3np0 combined 8
sudo ethtool -L enp0s4np0 combined 8
./build/app/RxTxApp --config_file tests/script/native_af_xdp_json/rss.json
> rss: support xdp

- tools/ebpf/README.md
- tools/ebpf/et.c
- tools/ebpf/et.h
This commit introduces the capability to load custom eBPF programs for
AF_XDP sockets within the tool. This enhancement allows users to specify
their own XDP programs, further extending the flexibility and usability
of the eBPF tools provided.
Usage: sudo ./et --prog xdp --ifname eth0,eth1 --xdp_path /path/to/xdp.o
> tools/ebpf: add support for loading custom AF_XDP prog

- CHANGELOG.md
- include/st20_api.h
- include/st20_redundant_api.h
- include/st30_api.h
- include/st40_api.h
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/pipeline/st20_pipeline_tx.c
- lib/src/st2110/pipeline/st22_pipeline_rx.c
- lib/src/st2110/pipeline/st22_pipeline_tx.c
- lib/src/st2110/redundant/st20_redundant_rx.c
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_video_session.c
- tests/src/st20p_test.cpp
- tests/src/st22p_test.cpp
- tests/src/st30_test.cpp
- tests/src/st40_test.cpp
For TX, set to zero to permit the library to generate a random synchronization source. 
For RX, assign zero to allow the library to disregard synchronization source checks.
> st2110: add ssrc support

- CHANGELOG.md
- app/src/args.c
- doc/run.md
- include/mtl_api.h
- lib/src/mt_log.h
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/mt_sch.c
- tests/script/kernel_socket_json/st20p.json
Add and a api `mtl_set_log_prefix_formatter` to customize the log prefix formatter. App can use "--log_time_ms" option to switch to a formatter with ms time accuracy.
> log: default add time info(seconds) print.

- app/meson.build
- app/tools/lcore_shmem_mgr.c
- app/tools/meson.build
- doc/lcore.md
- doc/run.md
- include/meson.build
- include/mtl_lcore_shm_api.h
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/mt_sch.c
- lib/src/mt_util.c
- lib/src/mt_util.h
usage:
--info: Print lcore shared manager detail info
--clean_pid_auto_check: Clean the dead entries if PID is not active
--clean_lcore <lcore id>: Clean the entry by lcore ID
> lcore: add LcoreMgr tool to manage the legacy lcore manager status

- doc/lcore.md
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/mt_sch.c
- lib/src/mt_sch.h
- lib/src/mt_tap.c
- lib/src/mt_util.c
- lib/src/mt_util.h
- lib/src/st2110/st_rx_video_session.c
output of ./build/app/LcoreMgr --info:
MT: 2023-11-14 15:00:03, mtl_lcore_shm_print, MTL used lcores 3
MT: 2023-11-14 15:00:03, mtl_lcore_shm_print, lcore 28 active by xxx@xxx, pid: 236759(comm: RxTxApp) type: app_allocated
MT: 2023-11-14 15:00:03, mtl_lcore_shm_print, lcore 29 active by xxx@xxx, pid: 236759(comm: RxTxApp) type: lib_sch
MT: 2023-11-14 15:00:03, mtl_lcore_shm_print, lcore 30 active by xxx@xxx, pid: 236759(comm: RxTxApp) type: lib_sch
MT: 2023-11-14 15:00:03, mtl_lcore_shm_print, collecting cpu usage
MT: 2023-11-14 15:00:04, mtl_lcore_shm_print, lcore 28 cpu usage 4.08%
MT: 2023-11-14 15:00:04, mtl_lcore_shm_print, lcore 29 cpu usage 100.00%
MT: 2023-11-14 15:00:04, mtl_lcore_shm_print, lcore 30 cpu usage 100.00%
> lcore: add cpu usage info LcoreMgr info command

- lib/src/mt_instance.c
- lib/src/mt_instance.h
- lib/src/mt_main.c
- manager/mtl_instance.hpp
- manager/mtl_interface.hpp
- manager/mtl_lcore.hpp
- manager/mtl_manager.cpp
- manager/mtl_mproto.h
1. Add interface module to manage NICs with kernel driver.
2. Use unique pointer for clients.
3. Refine log for instance.
4. Use singleton for lcore manager.
Next: add the XDP loader and replace the et tool.
> manager: allow register with interfaces

- lib/src/dev/mt_af_xdp.c
- lib/src/mt_main.h
- lib/src/st2110/st_tx_video_session.c
In our XDP program, packet headers are already filtered,
no need to do it in userspace again.
> dp/xdp: do not check pkt if xdp prog has done it

- lib/src/dev/mt_af_xdp.c
- lib/src/st2110/st_fmt.c
- manager/mtl_manager.cpp
xdp_tx return if prod_free < tx_full_thresh since the xsk_ring_prod is full already.
> xdp: add tx_full_thresh check

- lib/src/mt_ptp.c
- lib/src/mt_ptp.h
- lib/src/st2110/meson.build
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_ebu.c
- lib/src/st2110/st_rx_ebu.h
- lib/src/st2110/st_rx_video_session.c
- tests/script/loop_json/1080p59_1v.json
Make it easy to export the ebu info to the rx meta data, also display the ebu info in status.
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), COMPLIANT NARROW 598 WIDE 0 FAILED 1!
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), Cinst AVG 0.00 MIN 0 MAX 1!
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), VRX AVG 6.56 MIN -14 MAX 8!
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), Inter-packet time(ns) AVG 3891.32 MIN -1024 MAX 17408!
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), FPT AVG 613841.50 MIN 611429 MAX 617057 DIFF 5628!
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), LATENCY AVG 8294.69 MIN 387 MAX 17057!
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), RTP OFFSET AVG 54.50 MIN 54 MAX 55!
MT: 2023-12-01 16:41:25, rv_ebu_stat(0), RTP TS DELTA AVG 1501.50 MIN 1501 MAX 1502!
> rx/compliant: rework to frame level

- CHANGELOG.md
- app/sample/rx_st22_pipeline_sample.c
- app/sample/tx_st22_pipeline_sample.c
- app/src/parse_json.c
- app/src/parse_json.h
- app/src/rx_st20p_app.c
- app/src/rx_st22p_app.c
- app/src/tx_st20p_app.c
- app/src/tx_st22p_app.c
- app/src/tx_video_app.c
- include/st20_api.h
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_tx.c
- lib/src/st2110/pipeline/st22_pipeline_rx.c
- lib/src/st2110/pipeline/st22_pipeline_tx.c
- lib/src/st2110/pipeline/st22_pipeline_tx.h
- lib/src/st2110/st_fmt.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_video_session.c
- plugins/sample/st22_plugin_sample.c
- tests/script/loop_json/st22p_1v_1080i59.json
- tests/script/loop_json/st22p_interlaced_pcap.json
- tests/src/st22p_test.cpp
test with st22p_interlaced_pcap.json and st22p_1v_1080i59.json
> st22: add interlace support

- app/meson.build
- app/sample/experimental/rx_st20_redundant_combined_sample.c
- app/sample/meson.build
- app/sample/sample_util.h
- app/src/app_base.h
- app/src/rx_st20r_app.c
- include/experimental/st20_combined_api.h
- include/meson.build
- lib/src/st2110/experimental/meson.build
- lib/src/st2110/experimental/st20_redundant_combined_rx.c
- lib/src/st2110/experimental/st20_redundant_combined_rx.h
- lib/src/st2110/meson.build
It only used for the experimental header split. Rename to avoid the confuse from user side.
> api: move st20_redundant_combined to experimental

- lib/src/datapath/mt_dp_socket.c
- lib/src/dev/mt_af_xdp.c
- lib/src/dev/mt_dev.c
- lib/src/mt_main.h
- lib/src/mt_mcast.c
- lib/src/mt_ptp.c
- lib/src/mt_socket.c
- lib/src/mt_socket.h
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
1. Add source filter for kernel based backend.
2. Add multicast support for AF_XDP backend.
3. Fix condition for leave report sending.
> mcast: add source filter for kernel based backend

- docker/README.md
- docker/ubuntu.dockerfile
- manager/Dockerfile
Add the arguments needed to run AF_XDP backend.
> docker: add xdp deps in Dockerfile

- doc/run.md
- docker/README.md
- docker/docker-compose.yml
- docker/ubuntu.dockerfile
1. Update the run guide to use group for vfio access.
2. Update the Dockerfile to remove sudo for running.
3. Update the docker compose file.
> doc: use group to control access to vfio devices

- include/mtl_api.h
- lib/src/mt_main.c
- python/README.md
- python/example/st20p_rx.py
- python/example/version.py
- python/swig/.gitignore
- python/swig/pymtl.i
- python/swig/setup.py
- tests/src/tests.cpp
add some helper function for the python binding to array
> python: fix the mtl_init support

- rust/Cargo.toml
- rust/README.md
- rust/examples/version.rs
- rust/imtl-sys/Cargo.toml
- rust/imtl-sys/build.rs
- rust/imtl-sys/examples/no_std.rs
- rust/imtl-sys/src/convert.rs
- rust/imtl-sys/src/lib.rs
- rust/imtl-sys/src/pipeline.rs
- rust/imtl-sys/wrapper.h
- rust/imtl-sys/wrapper_convert.h
- rust/imtl-sys/wrapper_pipeline.h
- rust/src/imtl/convert/mod.rs
- rust/src/imtl/lib.rs
- rust/src/imtl/pipeline/mod.rs
- rust/src/imtl/version.rs
Only add the unsafe imtl-sys bindings, will add safer wrappers in the future.
> rust: add unsafe rust bindings

- CHANGELOG.md
- app/sample/sample_util.c
- app/src/args.c
- app/src/log.h
- doc/design.md
- ecosystem/obs_mtl/linux-mtl/mtl-input.c
- ecosystem/obs_mtl/linux-mtl/mtl-output.c
- include/mtl_api.h
- ld_preload/udp/udp_preload.h
- lib/src/dev/mt_dev.c
- lib/src/meson.build
- lib/src/mt_log.c
- lib/src/mt_log.h
- lib/src/mt_main.c
- lib/src/udp/ufd_main.c
- tests/src/tests.cpp
- tests/src/ufd_test.cpp
Applications can register a customized log printer using `mtl_set_log_printer`. Whenever MTL needs to log anything, the registered log callback will be invoked.
test with:
./build/app/RxTxApp --config_file tests/script/loop_json/1080p59_1v.json --log_printer
> log: add custom log printer

- app/src/args.c
fix error: implicit declaration of function ‘va_start’
> app: fix build fail as va_start in some setup

- lib/src/mt_rtcp.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/st_rx_video_session.c
- tests/src/st20p_test.cpp
Allow up to 256 fci in one NACK packet.
Testing RTCP with 10-15% loss rate passed.
> rtcp: set nack max fcis to 256

- include/mtl_api.h
- lib/src/dev/mt_dev.c
User can customize the maximum number of DPDK memzones by this option.
> init: add memzone_max option

- .gitignore
- python/README.md
- python/example/st20p_rx_encode.py
- python/example/st20p_tx.py
- python/example/st20p_tx_decode.py
python/example: add encode/decode support for rx/tx
test with:
python3 python/example/st20p_tx.py
python3 python/example/st20p_rx_encode.py
TX decode YUV video from an encoded file and transmit it as a ST2110
ST_FRAME_FMT_YUV422RFC4175PG2BE10 stream across the network.
RX receive a ST2110 ST_FRAME_FMT_YUV422RFC4175PG2BE10 stream and encode
the video stream to a `.mp4` encoder file.
> python/example: add encode/decode support for rx/tx

- app/src/args.c
- python/example/st20p_rx.py
- python/example/st20p_rx_encode.py
test with:
./build/app/RxTxApp --config_file tests/script/loop_json/1080p59_1v.json --p_port 0000:ac:01.1 --r_port 0000:ac:01.0
> app/args: allow override the port name when json config is used

- lib/src/st2110/st_header.h
- lib/src/st2110/st_tx_video_session.c
- tests/src/st20_test.cpp
- tests/src/st20p_test.cpp
remove the tx_done_cleanup and st22_min_pkts WA
test with:
./build/tests/KahawaiTest --auto_start_stop --p_port 0000:ac:01.2 --r_port 0000:ac:01.3 --nb_tx_desc 4096
> tx/video: use tx_no_chain mode if packets is less than buffered

- app/sample/rx_st20_pipeline_sample.c
- app/sample/rx_st20p_timing_parser_sample.c
- app/sample/tx_st22_pipeline_sample.c
- doc/design.md
- include/st20_api.h
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/pipeline/st20_pipeline_rx.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_timing_parser.c
- lib/src/st2110/st_rx_timing_parser.h
- lib/src/st2110/st_rx_video_session.c
- tests/src/st20p_test.cpp
test with:
./build/app/RxVideoTimingParserSample --p_port 0000:af:01.0 --r_port 0000:af:01.1
> rx/timing_parser: add -7 support

- tools/ebpf/.gitignore
- tools/ebpf/Makefile
- tools/ebpf/README.md
- tools/ebpf/lcore_monitor.c
- tools/ebpf/lcore_monitor.h
- tools/ebpf/lcore_monitor_kern.c
- tools/ebpf/log.h
usage:
sudo ./lcore_monitor --lcore 30 --t_pid 194145 --bpf_prog lcore_monitor_kern.o
> ebpf: add lcore_monitor tools

- include/st_convert_api.h
- include/st_convert_internal.h
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/st_convert.c
- lib/src/st2110/st_fmt.c
- python/example/misc_util.py
only scalar version now, only u and v for first line.
test with:
python3 python/example/st20p_rx.py --pipeline_fmt YUV420PLANAR8 --display
> convert: add rfc4175_422be10_to_yuv420p8

- tools/ebpf/lcore_monitor.c
- tools/ebpf/lcore_monitor.h
- tools/ebpf/lcore_monitor_kern.c
output like below:
lm_event_handler: sched out 5.315us as comm: migration/30
lm_event_handler: sched out 4.640us as comm: migration/30
lm_event_handler: sched out 5.304us as comm: migration/30
lm_event_handler: sched out 0.787us as irq: 348
lm_event_handler: sched out 1.248us as irq: 348
> lcore_monitor: add hook for irq entry/exit

- doc/run_WIN.md
- lib/src/mt_ptp.c
- lib/src/st2110/st_rx_video_session.c
test with:
./build/app/RxTxApp --config_file tests/script/loop_json/1080p59_1v.json --rx_timing_parser --p_port 0000:af:00.0 --r_port 0000:af:00.0
> timing_parser: fix timesync on pf without ptp gm

- ecosystem/ffmpeg_plugin/README.md
- ecosystem/ffmpeg_plugin/mtl_st20p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st22p_rx.c
align to standard naming of tx
> ecosystem/ffmpeg_plugin: use video_size, fps, pix_fmt as option name for rx

- patches/ice_drv/1.13.7/0001-vf-support-kahawai-runtime-rl-queue.patch
- patches/ice_drv/1.13.7/0002-ice-set-ICE_SCHED_DFLT_BURST_SIZE-to-2048.patch
- patches/ice_drv/1.13.7/0003-version-update-to-Kahawai_1.12.7_20231116.patch
- patches/ice_drv/1.13.7/xdp/0001-xdp-add-set-rate_kbps-support-for-the-tx_maxrate-sys.patch
I ported the patches to 1.13.7 ... Did not validate the code itself (other than verifying compilation)
> Port patches for 1.13.7 version.

- app/src/app_base.h
- app/src/rx_st20p_app.c
- app/src/rx_st22p_app.c
- app/src/rx_video_app.c
can be customized by args: `--rx_video_fb_cnt xxx`
(cherry picked from commit 03cff2776079889a47e98e30feb09087d39b2944)
> app: default video fb cnt to 3

- app/sample/legacy/tx_video_sample.c
- app/sample/sample_util.c
- app/sample/sample_util.h
- app/sample/tx_st20_pipeline_sample.c
- app/src/parse_json.c
- include/st20_api.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/pipeline/st20_pipeline_tx.c
- lib/src/st2110/st_fmt.c
- lib/src/st2110/st_fmt.h
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_video_session.c
- python/example/misc_util.py
- python/example/st20p_rx.py
- python/example/st20p_rx_encode.py
- python/example/st20p_tx.py
- python/example/st20p_tx_decode.py
- tests/script/loop_json/yuv422_planar10_transport.json
- tests/script/loop_json/yuv422_st20p_planar10_transport.json
- tests/src/st20p_test.cpp
For the case may not care the network bandwidth, the upper 6 bit of ST20_FMT_YUV_422_PLANAR10LE is always zero.
test with:
python3 python/example/st20p_tx.py --transport_fmt ST20_FMT_YUV_422_PLANAR10LE python3 python/example/st20p_rx.py --transport_fmt ST20_FMT_YUV_422_PLANAR10LE --display
> tx/video: add directly transport ST20_FMT_YUV_422_PLANAR10LE support

- app/src/parse_json.c
- include/st20_api.h
- lib/src/st2110/st_fmt.c
- python/example/misc_util.py
- tests/script/loop_json/v210_st20p_transport.json
- tests/script/loop_json/v210_transport.json
the display is very slow as the coverting take many steps.
test with:
python3 python/example/st20p_tx.py --tx_url v210_1080p.yuv --pipeline_fmt V210 --transport_fmt ST20_FMT_V210 --packing gpm
python3 python/example/st20p_rx.py --pipeline_fmt V210 --transport_fmt ST20_FMT_V210 --display
> python/example: add v210 display support

- app/src/args.c
- include/mtl_api.h
- lib/src/mt_main.h
- lib/src/mt_sch.c
- tests/src/tests.cpp
For case cores for the bind NUMA are all used, but please expect performance may drop as cross-numa ipi is expensive.
Test with:
./build/tests/KahawaiTest --p_port 0000:af:01.0 --r_port 0000:af:01.1 --gtest_filter=Sch.create_max --lcores 1,2,3,4,5 --allow_across_numa_core
> sch: add allow across numa core option

- CHANGELOG.md
- app/src/app_base.h
- app/src/args.c
- app/src/rx_audio_app.c
- app/src/rx_audio_app.h
- app/src/rxtx_app.c
- app/src/tx_audio_app.c
- include/st30_api.h
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_timing_parser.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_audio_session.c
test with:
./build/app/RxTxApp --config_file tests/script/audio_json/loop_125us_u32_96k.json --rx_timing_parser_meta --log_level warning --p_port 0000:af:00.0 --r_port 0000:af:00.1
> rx_timing_parser/audio: add callback notify support for application

- app/src/app_base.h
- app/src/args.c
- app/src/rx_audio_app.c
- app/src/tx_audio_app.c
- include/st30_api.h
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_tx_audio_session.c
test with:
./build/app/RxTxApp --config_file tests/script/audio_json/loop_redundant_125us_u32_96k.json --rx_timing_parser_meta --log_level warning --p_port 0000:af:00.0 --r_port 0000:af:00.1
> rx_timing_parser/audio: fix redundant status report

- tools/ebpf/Makefile
- tools/ebpf/README.md
- tools/ebpf/lcore_monitor.c
- tools/ebpf/lcore_monitor.h
- tools/ebpf/lcore_monitor_kern.c
`tracepoint/irq_vectors/irq_work_entry` support local_timer
> lcore_monitor: use irq_work_entry

- CHANGELOG.md
- tools/ebpf/.gitignore
- tools/ebpf/Makefile
- tools/ebpf/README.md
- tools/ebpf/lcore_monitor.c
- tools/ebpf/udp_monitor.bpf.c
- tools/ebpf/udp_monitor.c
- tools/ebpf/udp_monitor.h
promiscuous mode is enabled to detect all UDP on the network.
----- DUMP UDP STAT EVERY 2s -----
192.168.17.102:20076 -> 239.168.17.102:20000, 2611.027318 Mb/s pkts 493288
192.168.17.101:19955 -> 239.168.17.101:20000, 2610.995542 Mb/s pkts 493282
192.168.17.101:29892 -> 239.168.17.101:30000, 1.967996 Mb/s pkts 2000
192.168.17.102:29941 -> 239.168.17.102:30000, 1.967996 Mb/s pkts 2000
192.168.17.102:40070 -> 239.168.17.102:40000, 0.102720 Mb/s pkts 120
192.168.17.101:40054 -> 239.168.17.101:40000, 0.102720 Mb/s pkts 120
> tools/ebpf: add udp_monitor to sniff all UDP streaming on the network

- doc/design.md
- doc/usdt.md
- lib/meson.build
- lib/src/mt_log.c
- lib/src/mt_log.h
- lib/src/mt_main.c
- lib/src/mt_ptp.c
- lib/src/mt_usdt.h
- lib/src/mt_usdt_provider.d
It can be used to track the system in a production system where the log level is set to error only.
> usdt: add log_msg support

- lib/src/dev/mt_dev.c
- lib/src/dev/mt_rdma.c
- lib/src/mt_main.h
- lib/src/st2110/st_tx_video_session.c
These headers are redundant in RDMA UD datapath.
> rdma/ud: reduce l2/l3/l4 headers in data path

- CHANGELOG.md
- app/src/args.c
- doc/run.md
- include/mtl_api.h
- lib/src/mt_main.h
- lib/src/mt_mcast.c
- lib/src/st2110/st_header.h
- lib/src/st2110/st_rx_ancillary_session.c
- lib/src/st2110/st_rx_audio_session.c
- lib/src/st2110/st_rx_video_session.c
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_video_session.c
For the SDN switch case which dispatch the stream directly.
Also refine the uinit routine for error handling in the attach.
> mcast: add MTL_FLAG_NO_MULTICAST option

- app/src/args.c
- doc/run.md
- include/mtl_api.h
- lib/src/dev/mt_dev.c
- lib/src/mt_main.h
- lib/src/mt_sch.c
VF ptp may require a dedicated lcore for accuracy.
> mtl: add dedicated lcore options for sys tasks

- app/src/args.c
- doc/run.md
- include/mtl_api.h
- lib/src/mt_main.c
- lib/src/mt_main.h
- lib/src/mt_sch.c
- rust/imtl-sys/examples/no_std.rs
MTL_PORT_FLAG_FORCE_NUMA is introduced to force the numa id for each port.
test with:
./build/app/RxTxApp --config_file tests/script/loop_json/4kp59_1v.json --force_numa 0
> mtl: add force numa option

- manager/mtl.xdp.c
- manager/mtl_interface.hpp
BPF_MAP_TYPE_ARRAY size is limited cause udp4_dp_filter_fd update fail(-7)
> xdp: use BPF_MAP_TYPE_HASH for the filter map

- lib/src/mt_cni.c
- lib/src/mt_main.h
- lib/src/udp/udp_rxq.c
- lib/src/udp/ufd_main.c
Fix below fail:
MTL: 2024-06-15 00:45:30, mt_asan_check, leak of 1624 byte(s) at 0x7fc17ff3b900
MTL: 2024-06-15 00:45:30, mt_asan_check, backtrace info:
MTL: 2024-06-15 00:45:30, mt_asan_check, /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7fc9823fdd40]
MTL: 2024-06-15 00:45:30, mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(mt_rte_zmalloc_socket+0x18a) [0x7fc981d07c69]
MTL: 2024-06-15 00:45:30, mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(+0x6ecbfe) [0x7fc982200bfe]
MTL: 2024-06-15 00:45:30, mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(+0x6ed322) [0x7fc982201322]
MTL: 2024-06-15 00:45:30, mt_asan_check, /usr/local/lib/x86_64-linux-gnu/libmtl.so(mufd_socket_port+0x132) [0x7fc982201b26]
MTL: 2024-06-15 00:45:30, mt_asan_check, …
> ufd: fix memleak detected by mt_asan_check

- app/sample/sample_util.c
- include/mtl_api.h
- lib/src/dev/mt_dev.c
- lib/src/mt_sch.c
- rust/imtl-sys/examples/no_std.rs
The Core ID that is used as DPDK main thread.
> dpdk: add main_lcore support

- lib/src/st2110/st_video_transmitter.c
- lib/src/udp/udp_main.c
During the budling MTL with debugoptimized there are some errors with maybe-uninitialized variables
`./build.sh debugoptimized`
This PR should fix this issue
> fix(build): fixing 'maybe-uninitialized' errors for 'debugoptimized' build

- ecosystem/ffmpeg_plugin/mtl_common.c
- ecosystem/ffmpeg_plugin/mtl_st20p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st20p_tx.c
- ecosystem/ffmpeg_plugin/mtl_st22p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st22p_tx.c
- ecosystem/ffmpeg_plugin/mtl_st30p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st30p_tx.c
Address an issue where the RX is sending
ARP replies to the TX while still being completely uninitialized, which leads to the session dropping frames. The problem worsens as the TX outperforms
the RX in terms of initialization speed.
Resolve this by halting the FFmpeg plugin
initialization and starting the scheduled tasklets because we don't want the CNI thread to respond to the ARP requests sent in the tv_attach function
until the RX is ready to receive those packets.
> Fix RX side dropping frames at the beginning.

- manager/Dockerfile
- manager/README.md
Addresses the build failure in the MTL Manager
Docker configuration due to a missing VERSION file. Ensures the VERSION file is properly included.
Co-developed-by: Aleksandr Ivanov <aleksandr.ivanov@intel.com>
Fixes: 56f207d4
> Fix Docker build issue in MTL Manager

- ecosystem/ffmpeg_plugin/mtl_common.c
- ecosystem/ffmpeg_plugin/mtl_st20p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st20p_tx.c
- ecosystem/ffmpeg_plugin/mtl_st22p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st22p_tx.c
- ecosystem/ffmpeg_plugin/mtl_st30p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st30p_tx.c
Address an issue where the RX is sending
ARP replies to the TX while still being completely uninitialized, which leads to the session dropping frames. The problem worsens as the TX outperforms
the RX in terms of initialization speed.
Resolve this by halting the FFmpeg plugin
initialization and starting the scheduled tasklets because we don't want the CNI thread to respond to the ARP requests sent in the tv_attach function
until the RX is ready to receive those packets.
> ecosystem/ffmpeg: improve unicast initial (#917)

- lib/src/dev/mt_dev.c
- lib/src/mt_main.h
This PR adds support for the IXGBE driver, according #930 . 
Both the Intel 10-Gigabit X540-AT2 (1528) and Intel 10G X550T (1563) have been tested. In the test where PF was used to bind with the PMD, both RxTxApp and ffmpeg-plugin app transmit media successfully.
> add support for ixgbe driver

- lib/src/mt_sch.c
Fix the scheduler API issue where using
the scheduler API binds all user-created
schedulers to socket_id 0. The problem arises when socket_id = 1; while the first scheduler is
correctly assigned, all subsequent user-created
schedulers default to socket_id 0.
> fix sch api not binding user schedulers to numa

- lib/src/mt_sch.c
When mt_sch_put_lcore is called with an incorrect
lcore ID while using mtl_manager, the error log
attempts to access out-of-bounds memory, causing
a segmentation fault
Add check that will prevent this issue
> fix out-of-bounds segfault in mt_sch_put_lcore

- lib/src/st2110/pipeline/st22_pipeline_tx.c
In ST22, ensure the frame status changes to FREE
at the end of transmitting the last frame.
This change addresses the issue of the last frame
sometimes being omitted in ST22 streams.
> Fix the last frame drop in ST22

- app/src/parse_json.c
- lib/src/mt_util.h
This PR fixes #946 by fixing the upper limits of the conditional in [`lib/src/mt_util.h:92`](https://github.com/OpenVisualCloud/Media-Transport-Library/blob/ddcc0413559274f7ba83e8cf1141aa0b2bfba137/lib/src/mt_util.h#L92) and [`app/src/parse_json.c:467`](https://github.com/OpenVisualCloud/Media-Transport-Library/blob/ddcc0413559274f7ba83e8cf1141aa0b2bfba137/app/src/parse_json.c#L467).
> Fix incorrect upper bound of RTP payload validity check (#946)

- lib/src/st2110/pipeline/st22_pipeline_rx.c
- lib/src/st2110/pipeline/st22_pipeline_tx.c
Fix ST22P create session functions ignoring
socket_id values, which causes the sessions to
allocate memory on socket 0 regardless of the
session NUMA range.
- Ensure socket_id is correctly handled during session creation.
- Prevent memory allocation on incorrect sockets.
> Fix ST22P session creation socket ID

- app/src/parse_json.c
- app/src/tx_fastmetadata_app.c
- lib/src/st2110/st_tx_fastmetadata_session.c
* Fix possible null pointer reference in app_tx_fmd_init
* Fix: coveriy out of band issue
* Increate quality of tx_fastmetadata_session_build_packet code
* coverity fix:  fixing less-than-zero comparison
* add st41 context app multithread access error
* Add error message when the st41 functionality of RxTx app detects multithread access to the contex
app resource, which should not be shared.
Fixes: c43152d9
Co-developed-by: Aleksandr Ivanov <aleksandr.ivanov@intel.com>
Co-developed-by: Kolelis, Szymon <szymon.kolelis@intel.com>
> Fix: fix and refactor st41 possible errors

- lib/src/st2110/st_tx_fastmetadata_session.c
In the FMD build packet, we were checking
the space using a value that represented 4-byte
chunks. This has been fixed by multiplying the
value by 4.
Fixes: 664344a8
Co-authored-by: Kolelis, Szymon <szymon.kolelis@intel.com>
> Fix: FMD Adjust the Space Memory Check

- ecosystem/ffmpeg_plugin/mtl_st30p_rx.c
- ecosystem/ffmpeg_plugin/mtl_st30p_tx.c
Commit 065923f3f768 ("Refactor FFmpeg audio plugin sample rate parsing") added a helper function for parsing the sample frequency. However, the error returned from the function was checked incorrectly (inverted). This led to a segmentation fault when starting FFmpeg with MTL audio plugins.
This commit fixes the error handling by checking if the return value is non zero.
Fixes: 065923f3f768 ("Refactor FFmpeg audio plugin sample rate parsing")
Change-type: DefectResolution
> Fix: error handling in parsing sample freq in FFmpeg audio plugins

- app/src/app_base.h
- app/src/tx_ancillary_app.c
- app/src/tx_fastmetadata_app.c
Fix hardcoded payload type in RTP mode in the RxTxApp for st40 and st41 cases.
fixes: c43152d
fixes: 19f3e16
> Fix: fix the enforced (hardcoded) payload types in RTP mode for ST41 and ST40

- ecosystem/gstreamer_plugin/gstmtltxsink.c
- ecosystem/gstreamer_plugin/gstmtltxsink.h
- ecosystem/gstreamer_plugin/meson.build
add simple st20tx plugin for gstreamer, allows for simple st2110 tx stream creation.
Known bugs
Tested against the ffmpeg st20 rx plugin and found corruption in the video stream. This is likely due to frame creation mechanizm in the _chain function
Working on fixing it now
> Add: simple st20tx plugin for gstreamer

- ecosystem/gstreamer_plugin/gstmtltxsink.c
- ecosystem/gstreamer_plugin/gstmtltxsink.h
Fix 73-byte corruption in the top left corner
The issue was caused by using void pointers
instead of the proper GStreamer memory
management functions. This led to memory
structures being saved in the output stream,
causing corruption in the top left corner.
Cleanup the code
Make the _chain function much simpler without
any lingering frames in the _mtltxsink
structure.
Add support for framebuffer argument
Add support for fps argument that overrides the
framerate of the capabilities.
Fix Ensure Gstreamer plugin reaches PLAYING state
Force the Gstreamer plugin into the PLAYING state
to prevent reinitialization of the pipeline.
This is achieved by disabling ASYNC state handling
and manually setting the state to PLAYING.
Additionally, send EOS when it is received,
to signal the end of …
> Fix: gstreamer top left corruption and states

- script/build_dpdk.sh
The `git am` command does use a path which drills down too little (does not hit the `patches` folder) and fails the script entirely.
> Fix: build_dpdk.sh - git am command path

- lib/src/mt_flow.c
DPDK backend flow rules are failing on the E810 PF when ETH rules are ignored on
the default attribute group 0.
Flow rules are used to filter the data coming from queues, and by default,
attribute group 0 should be used. Applying the filters should not fail when the
flow validation function passes. However, this does not happen when we use
filters with the ETH segment set to NULL on E810 physical cards (it works fine
on the virtual NICs hosted on the same NIC).
Fix this problem for now by reapplying the flow rules when the verification
fails in this specific scenario.
This code should be deleted when the E810 PF NIC stops failing to apply
flow rules in this specific scenario.
> Fix: flow rules failing after verification on PF

- ecosystem/gstreamer_plugin/gst_mtl_common.c
- ecosystem/gstreamer_plugin/gst_mtl_common.h
- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.h
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.h
- ecosystem/gstreamer_plugin/meson.build
Create a plugin for st20p rx standard
for GStreamer, allowing to receive the data in the
pipeline mode.
Create a simple design where we create
the session in the _start function, 
receive and process in _create function.
Move some of the functions from the TX  to the
common file.
Change the name of the TX plugin to mtl_st20p_tx to
make it easier to distinguish between the plugins.
>    Add: src rx st20 plugin for gstreamer

- ecosystem/gstreamer_plugin/gst_mtl_common.c
- ecosystem/gstreamer_plugin/gst_mtl_common.h
- ecosystem/gstreamer_plugin/gst_mtl_st40_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40_rx.h
- ecosystem/gstreamer_plugin/meson.build
Add a plugin for gstreamer that can handle
ancillary data. The plugin is using non-pipline
as there is non pipline api for st40.
Pads capabilies are set as gstreamer plugins
dosn't seem to follow any set standard for
ancillary caps.
To test, setup RxTxApp
"ancillary": [
{
"replicas": 1,
"start_port": 40000,
"payload_type": 113,
"type": "frame",
"ancillary_format": "closed_caption",
"ancillary_url": "./test.txt",
"ancillary_fps": "p59"
}]
Move part of the initalization that will repeat
itself to the gst_mtl_common.
Introduce generall parameters for all gstreamer
mtl plugins to use.
Use simple timed out mutexes for the blocking
mechanism.
> Add: plugin for gstreamer ancillary data

- ecosystem/gstreamer_plugin/gst_mtl_common.c
- ecosystem/gstreamer_plugin/gst_mtl_common.h
- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.h
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.h
- ecosystem/gstreamer_plugin/gst_mtl_st30p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_rx.h
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.h
- ecosystem/gstreamer_plugin/gst_mtl_st40_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40_rx.h
- ecosystem/gstreamer_plugin/meson.build
Using functions from gst_mtl_common to make all
arguments in gstreamer plugins cross compatible,
order the arguments in the header files.
> Fix: unify gstreamer arguments across plugins

- ecosystem/gstreamer_plugin/README.md
Add GStreamer plugins documentation
- Detailed instructions for building the plugins.
- Example usage of the plugins.
- Run instructions for various scenarios.
> Docs: GStreamer documentation

- README.md
- doc/aws.md
- doc/compliance.md
- doc/design.md
- doc/dma.md
- doc/run.md
- doc/run_WIN.md
- doc/sdm_appliance.md
- ecosystem/ffmpeg_plugin/README.md
- manager/README.md
- fixes for images tags (replacement <img> HTML tags with ![] Markdown tag) (working wrong in Sphinx)
- images descriptions fixes (removing "png" from image descriptions)
- images descriptions fixes (replacing "image" with more meaningful names)
- local paths (in the same directory) to pictures/other documents - unified to have no "./" at the beginning
> Docs: fixes for images and paths

- ecosystem/gstreamer_plugin/README.md
- ecosystem/gstreamer_plugin/gst_mtl_common.c
- ecosystem/gstreamer_plugin/gst_mtl_common.h
- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40p_tx.c
- ecosystem/gstreamer_plugin/meson.build
MTL common handle support in GStreamer
- Add ability to use the same MTL instance for
multiple GStreamer plugin instances in the same
pipeline.
- Change the default behavior of the MTL GStreamer
plugins to make all subsequent plugins ignore
dev arguments after the first one.
After this change only one MTL library process
is spawned per pipeline.
- Add a new module called gst_common to hold
the address of the MTL instance.
- Update documentation to include a warning about
the behavior change.
> Add: MTL common handle support in GStreamer

- README.md
- doc/sphinx/conf.py
link to main docs added (#1056 on main)
Docs:
- removed release from Sphinx docs title 
- link to main webpage of docs added at the beginning of main README.md file -> [-
https://github.com/OpenVisualCloud/Intel-Tiber-Broadcast-Suite/pull/58](https://openvisualcloud.github.io/Media-Transport-Library/)
> Docs: removed release from Sphinx docs title and link to main docs

- .github/workflows/ubuntu_build_with_gtest.yml
Update `ubuntu_build_with_gtest.yml` (gtest) for a better naming convention.
> Update gtest jobs for a better naming convention.

- tests/unittest/st20p_test.cpp
Gtests are failing when running the vsync with
kernel:lo interface. Due to the high single-core
performance toll. Test will be omitted on kernel:lo.
> Fix: gtests fails vscync with kernel:lo

- .github/workflows/trivy.yml
* fix cron syntax in step condition in trivy.yml
* update other jobs with conditional schedule
> Fix: trivy fails on scheduled jobs

- ecosystem/gstreamer_plugin/README.md
- tests/validation/tests/single/gstreamer/video_resolution/test_video_resolution.py
- tests/validation/tests/xfail.py
- Add disclaimer about 720p in docs.
- The 720p resolution is not supported by MTL for v210 at the moment. This is a MTL bug, but the GStreamer plugin does not need to support it.
> Fix: Remove unsupported 720p resolution from tests

- doc/configuration_guide.md
- tests/validation/tests/single/audio/audio_channel/test_audio_channel.py
Adjust ptime to 0.33 ms for "222" audio channel with PCM16 or PCM24 formats to accommodate the packet size.
> Fix: Update audio channel tests.

- lib/src/dev/mt_af_xdp.c
xsk_umem__create can return positive and negative values as error codes
> Fix: error handling in mt_af_xdp.c

- .github/workflows/gtest-bare-metal.yml
FIX: gtest-bare-metal.yml workflow failing
REFACTOR: removed DPDK build for each bare metal run as it does not change often - this will be added later as an optional for workflow dispatch.
> FIX: gtest-bare-metal.yml workflow failing

- ecosystem/gstreamer_plugin/README.md
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.h
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.h
If session startup time is critical, it is possible to launch a session in the background.
This will allow the GST pipeline to be running while the session is being created.
All buffers will be dropped until the session is ready.
> Add: Option to launch a session in the background

- ecosystem/gstreamer_plugin/gst_mtl_common.c
- ecosystem/gstreamer_plugin/gst_mtl_common.h
- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40p_tx.c
Fix gst mtl shared plugin deinitialization
function naive approach to the plugins in the
shared pipline space, making sure the
plugins cannot abuse the shared counter by
reseting their handle to NULL>
> Fix: deinitialization of the shared plugin crash

- .gitignore
Add logging directories to .gitignore for the
reproduction automatic tests for GStreamer.
> Add: logging directories to .gitignore

- include/mtl_api.h
- lib/src/dev/mt_dev.c
Mtl could not initialize when forced to use
0 as main_lcore in lcore restrained environments,
like docker containers.
Change this by making the dpdk initialize
automatically when the main_lcore is 0.
> Fix: forcing mtl to initialize on lcore 0

- ecosystem/ffmpeg_plugin/mtl_common.c
- ecosystem/ffmpeg_plugin/mtl_common.h
Add support for queue number arguments in FFmpeg
plugins so that mtl can be configured from the
user application.
> Add: FFmpeg support for queue number arguments

- doc/run.md
Change the run to inlcude warning about MtlManager as clinets are oftentimes running into lcore
assigmnet issues which could be avoided by
signaling them to use MtlManager in clear enough
form.
> Docs: add warning about MtlManager in the run.md

- doc/coding_standard.md
Add simple coding standard documentation that can
serve as preqursor for all future coding quality
knowledge hub.
> Docs: add coding standard documentation

- .github/workflows/afxdp_build.yml
- .github/workflows/afxdp_build_with_gtest.yml
- .github/workflows/codeql.yml
- .github/workflows/dpdk_patches_build.yml
- .github/workflows/gtest-bare-metal.yml
- .github/workflows/msys2_build.yml
- .github/workflows/msys2_ffmpeg.yml
- .github/workflows/ubuntu_build.yml
- .github/workflows/validation-tests.yml
- .github/workflows/windows_build_with_gtest.yml
- action.yml
- doc/build.md
- doc/build_WIN.md
- docker/ubuntu.dockerfile
- lib/src/dev/mt_dev.c
- lib/src/mt_main.h
- lib/src/mt_util.c
- patches/dpdk/25.03/0001-e810-set-max-ring-desc-to-max-allowed-by-hardware.patch
- patches/dpdk/25.03/0002-net-iavf-refine-queue-rate-limit-configure.patch
- patches/dpdk/25.03/0003-ice-set-ICE_SCHED_DFLT_BURST_SIZE-to-2048.patch
- patches/dpdk/25.03/0004-Change-to-enable-PTP.patch
- patches/dpdk/25.03/0005-iavf-disable-runtime-queue.patch
- patches/dpdk/25.03/0006-pcapng-add-user-timestamp-support.patch
- patches/dpdk/25.03/hdr_split/0001-net-intel-ice-support-hdr-split-mbuf-callback.patch
- script/build_dpdk.sh
-  Add patches for DPDK 25.03, `0003-net-ice-revert-PF-ICE-rate-limit-to-non-queue-group-.patch` was dropped
- align mt_ipv4_udp to two-byte boundary: `mt_ipv4_udp` has to be aligned after c14fba6 commit from DPDK.
This commits adds alignment to `rte_ipv4_hdr` structure, which adds
the same requirement to all structures that starts with `rte_ipv4_hdr`.
- unhandled ret from rte_eth_link_get_nowait
> Add: support for DPDK 25.03

- ecosystem/gstreamer_plugin/gst_mtl_common.c
In gstreamer common code fix the redundant udp
port parameter overwriting the primary port
parameter.
> Fix: gstreamer plugins redundant udp parameter

- tests/tools/RxTxApp/src/parse_json.c
Change the parser to accept the lack of a URL parameter
for rx session, as we can ignore the input and no
json examples have this included.
fixes: 353b64b595e85fc4e1e6ce078b2c3b1fad906db5
> Fix: RxTxApp requires a JSON url parameter

- ecosystem/gstreamer_plugin/README.md
- ecosystem/gstreamer_plugin/gst_mtl_st30p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.c
Adjust the capabilities of the GStreamer audio
A plugin to support the ST30P 8 channels.
> Fix: GStreamer audio plugin capabilities

- README.md
Delete the icons / links to github actions
that had no working github actions behind them.
Fixes: b9e266d84fc1ba132dc9acf536a5a21d82dd2579
> Fix: github actions icons not working

- lib/src/dev/mt_dev.c
- lib/src/mt_cni.c
- lib/src/mt_main.h
- Use an eight-level hierarchical schedule for PF
- Don't use shapers for non-leaf nodes, as thier rules are now correctly inherated to leaf nodes
- Stop calling rte_eth_rx_burst() while rte_tm_hierarchy_commit() is in progress, as it causes error logs.
- Rename dev_rl_init_root to dev_rl_init_nonleaf_nodes and move it out of dev_rl_shaper_add
> Fix: RL pacing on DPDK 25.03

- doc/experimental/performance_optimizations.md
ADD: Create `doc/experimental/performance_optimizations.md` with know how basics on kernel and generally OS level related optimizations.
> Add: Create performance_optimizations.md

- versions.env
ADD: Create `versions.env` with basic variables regarding latest recommended versions, that include the following:
- DPDK driver version and link
- ICE driver version and link
- IRDMA driver version and link
To use it, user can source it in his shell session and refer to params by name or use it as a reference for manual download of dependencies.
From now on every version of packages that are mandatory for this repository should be defined and updated in this file.
> ADD: Create versions.env with basic variables

- ecosystem/gstreamer_plugin/README.md
- ecosystem/gstreamer_plugin/gst_mtl_st20p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st30p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40p_tx.c
- ecosystem/gstreamer_plugin/gst_mtl_st40p_tx.h
- include/experimental/st40_pipeline_api.h
- include/st40_api.h
- lib/src/st2110/experimental/st40_pipeline_tx.c
- lib/src/st2110/experimental/st40_pipeline_tx.h
- lib/src/st2110/st_tx_ancillary_session.c
- tests/tools/RxTxApp/src/rx_ancillary_app.c
- tests/tools/RxTxApp/src/tx_ancillary_app.c
- tests/unittest/st40_test.cpp
Add support for 8331 adjacent ancillary data
input for the GStreamer st40 ancillary data plugin.
Which allows the user to take input from 
https://www.[ietf.org/rfc/rfc8331.html](https://www.ietf.org/rfc/rfc8331.html)
Starting ANC_Count  and ending with word_align.
Add support for buffer size for UDW support
that allows the user to change the size of the
buffers, set it to the maximum by default 
as the wasted size of appropriately 
2kb * framebuffer count is acceptable.
Change the st40p api to hide the metadata,
which should be clearer for users. 
Refactor: Isolate the parsing of data into
gst_mtl_st40p_tx_parse_*  functions.
Fix the issue with the GST buffer size being taken from
the whole GstBuffer instead of the mapped
GstMemory.
> Add: GStreamer plugin 8331 input support

- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.c
- ecosystem/gstreamer_plugin/gst_mtl_st20p_rx.h
Add to GStreamer ST20 RX plugin zero-copy MTL implementation,
Initial testing shows performance gains.
Introduce 2 paths, as the path without conversion in put_frame
is "aligning" the memory for the zero-copy path to work, without
It we need to do the memory alignment in the element.
The memcpy path should not be hit unless we unlock the caps
for the rfc4175_422be10 that allows for transfer without translation.
> Add: Gstreamer ST20 RX zero copy

- lib/src/mt_sch.c
If MTL is not gracefully shutdown, then lcore shared memory can gets into a bad state. Check if PID of specified lcore is active, if no then release it
> Fix: MTL lcore management gets into a bad state

- doc/build.md
In order to run ./configure in libpcap (1.2.2.), flex or lex and yacc/byacc must be installed.
Tested on Ubuntu 22.04.5 LTS.
```text
$ git clone https://github.com/the-tcpdump-group/libpcap.git -b libpcap-1.9
cd libpcap/
./configure
Cloning into 'libpcap'...
remote: Enumerating objects: 35600, done.
remote: Counting objects: 100% (595/595), done.
(...)
checking whether to build optimizer debugging code... no
checking whether to build parser debugging code... no
checking for flex... no
checking for lex... no
configure: error: Neither flex nor lex was found.
$ sudo apt install flex
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
libfl-dev libfl2 m4
Suggested packages:
bison flex-doc m4-doc …
```
> Docs: flex and byacc as required packages for libpcap in build.md

- lib/src/st2110/st_rx_video_session.c
* The error counter is incremented for each individual packet that fails (handler_ret < 0), providing more accurate per-packet error statistics.
* The return value from rv_handle_mbuf is now checked. If it is negative, an debug message in bulk for whole iteration  is logged.
> Fix: handler return error

- lib/src/mt_stat.c
The current implementation may miss some of the
registered statistics callbacks alarms causing
segfault.
The stats thread can run the statystics after
stats_thread stopping
MTL: stat_thread, stop
MTL: * *    M T    D E V   S T A T E   * *
MTL: * *    E N D    S T A T E   * *
Use the generic handler deregistration
that ensures all registered callbacks are cleaned
up properly.
> Fix: incorrect cleanup of the stats alarm handler

- app/meson.build
- app/perf/meson.build
- app/perf/p16le_to_rfc4175_422be10.c
- app/perf/perf_test.sh
- app/perf/rfc4175_422be10_to_p16le.c
- app/tools/convert_app.c
- app/tools/convert_app_args.c
- app/tools/convert_app_base.h
- include/st_convert_api.h
- include/st_convert_internal.h
- include/st_pipeline_api.h
- lib/src/st2110/pipeline/st20_pipeline_rx.c
- lib/src/st2110/st_avx512.c
- lib/src/st2110/st_avx512.h
- lib/src/st2110/st_convert.c
- lib/src/st2110/st_fmt.c
- lib/src/st2110/st_fmt.h
- plugins/sample/convert_plugin_sample.c
- tests/tools/RxTxApp/src/parse_json.c
- tests/unittest/cvt_test.cpp
added FRAME_FMT_YUV422PLANAR16LE, implemented conversion to and from RFC4175_42210BE in scalar and AVX512
> Add: support for planar16le

- lib/src/st2110/st_tx_video_session.c
Commit wrongly reversed the order of allocation
time for enw pacing start time.
Reverse it back.
Fixes: acea200ef8c935cdff64b04a46951bfd4b67f8f0
> Fix: calculating pacing start_time

- .github/scripts/setup_environment.sh
- ecosystem/gstreamer_plugin/build.sh
Using relative paths for build script made it
prone to fail and to produce unexpected results
when executed from different working directories.
Add a check to ensure the script always runs from
its own directory.
Fixes: 12098baf5f94d18983954c265aa3783851c8869d
> Fix: GSstreamer build script path resolution

- tests/validation/requirements.txt
As part of CVE-2025-50817 mitigation removed future package from the requirements.txt for validation framework
> Fix: CVE-2025-50817 mitigation

- .github/workflows/nightly-tests.yml
- .github/workflows/smoke-tests.yml
Running the test framework with sudo causes root to become the owner of some directories. This causes problems with permissions when trying to checkout in workflows.
Run the framework without sudo. Remove the no longer needed chown step in the workflow.
> Ci: Run test framework without sudo in workflows

- config/tx_1v_user_pacing.json
- doc/design.md
- lib/src/st2110/st_fmt.c
- lib/src/st2110/st_tx_ancillary_session.c
- lib/src/st2110/st_tx_audio_session.c
- lib/src/st2110/st_tx_fastmetadata_session.c
- lib/src/st2110/st_tx_video_session.c
- tests/tools/RxTxApp/src/app_base.h
- tests/tools/RxTxApp/src/args.c
- tests/tools/RxTxApp/src/parse_json.c
- tests/tools/RxTxApp/src/parse_json.h
- tests/tools/RxTxApp/src/rxtx_app.c
- tests/tools/RxTxApp/src/tx_st20p_app.c
- tests/tools/RxTxApp/src/tx_st30p_app.c
- expose user_timestamp as json parameter for RxTxApp
- Align timestamps created by RxTxApp to N*frame_time
- Add small fix to the lib: For user_pacing now it aligns to the closest N*frame_time instead of the last.
> Add: user_timestamp as json parameter for RxTxApp

- .github/actions/build/action.yml
Replace the old FFmpeg build code with the currently used build script in the build composite action used in smoke and nightly tests.
> Ci: Fix FFmpeg build

- ecosystem/ffmpeg_plugin/mtl_common.h
Add support for redundant mode in FFmpeg plugin
by enabling parameters.
> Add: FFmpeg support for redundant mode
