OpenVisualCloud/Media-Transport-Library

app/sample/rx_st20_redundant_sample.c, include/st20_dpdk_api.h, include/st20_redundant_api.h, include/st_pipeline_api.h, lib/src/pipeline/st20_pipeline_rx.c, lib/src/redundant/st20_redundant_rx.c, lib/src/st_admin.c, lib/src/st_cni.c, lib/src/st_rx_video_session.c, lib/src/st_rx_video_session.h, tests/script/1080p30_1v.json, tests/script/1080p60_1v.json, tests/script/redundant/hdr_split_tx.json
=> st20r: add hdr split support

.github/workflows/clang_build.yml, README.md, app/src/rx_ancillary_app.c, app/src/rx_audio_app.c, app/src/rx_st20p_app.c, app/src/rx_st22p_app.c, app/src/rx_video_app.c, app/src/tx_video_app.c, lib/src/st_admin.c, lib/src/st_ptp.c, tests/script/afxdp_test.sh, tests/script/hdr_split_test.sh, tests/script/loop_ebu_test.sh, tests/script/loop_test.sh
=> CI: add clang build

app/meson.build, build.sh, lib/src/st_main.h, lib/src/st_quirk.h, lib/src/st_tx_video_session.c, lib/src/st_video_transmitter.c, meson.build, plugins/meson.build, plugins/obs-kahawai/linux-kahawai/meson.build, plugins/st22_ffmpeg/meson.build
fix panic(memory corrupt) under ubuntu clang build
=> clang: add quirk for dequeue_bulk

include/st20_dpdk_api.h, lib/src/st_main.h, lib/src/st_rx_video_session.c, lib/src/st_tx_video_session.c, tests/src/st20_test.cpp
=> st20: add linesize support for BPM/GPM packing

.github/workflows/centos_build.yaml, .github/workflows/clang_build.yml, .github/workflows/dpdk_patches_build.yml, .github/workflows/ubuntu_build.yml, CHANGELOG.md, build.sh, doc/build.md, lib/src/st_platform.h, meson.build, meson_options.txt
=> CI: use prebuilt dpdk lib

.github/workflows/dpdk_patches_build.yml
=> CI: fix dpdk_patches_build yml

app/src/app_base.h, app/src/args.c, app/src/parse_json.c, app/src/parse_json.h, app/src/rxtx_app.c, doc/configuration_guide.md, doc/run.md
use "display" field in json to control SDL init
=> app: remove display option

app/src/rx_st22p_app.c
Support yuv422packed8 display for rx_st22_pipline application.
=> app: support yuv422packed8 display

app/sample/rx_st20_pipeline_sample.c, include/st20_dpdk_api.h, include/st_pipeline_api.h, lib/src/pipeline/st20_pipeline_rx.c, lib/src/st_rx_video_session.c, tests/src/st20_test.cpp, tests/src/st20p_test.cpp
=> st20(p): add metadata for query_ext_frame api

CHANGELOG.md, build.sh, include/st20_dpdk_api.h, include/st30_dpdk_api.h, include/st40_dpdk_api.h, include/st_dpdk_api.h, include/st_pipeline_api.h, lib/src/pipeline/st20_pipeline_tx.c, lib/src/pipeline/st22_pipeline_tx.c, lib/src/st_main.h, lib/src/st_tx_ancillary_session.c, lib/src/st_tx_audio_session.c, lib/src/st_tx_video_session.c, tests/src/st20_test.cpp, tests/src/st20p_test.cpp, tests/src/st22_test.cpp, tests/src/st22p_test.cpp, tests/src/st30_test.cpp, tests/src/st40_test.cpp, tests/src/tests.h
=> tx/video: add ST20_TX_FLAG_USER_PACING support

.github/workflows/dpdk_patches_build.yml, .github/workflows/ubuntu_build_with_gtest.yml
=> CI: gtest action only when lib changes

lib/src/st_main.h, lib/src/st_rx_video_session.c, lib/src/st_tx_video_session.c, tests/src/st20p_test.cpp, tests/src/st22p_test.cpp, tests/src/tests.h
=> test/st20p/st22p: add user timestamp test

app/meson.build, include/st_pipeline_api.h, lib/src/st_platform.h, lib/src/st_sch.c, lib/windows/win_posix.h
=> windows: fix build with pthread_cond_timedwait

.github/workflows/clang_build.yml, .github/workflows/ubuntu_build.yml, CHANGELOG.md, app/meson.build, app/meson_options.txt, build.sh, doc/asan.md, lib/meson.build, lib/src/st_main.c, lib/src/st_mem.h, meson_options.txt, plugins/meson.build, plugins/meson_options.txt, tests/meson.build, tests/meson_options.txt
1. Build dpdk with -Db_sanitize=address
2. ST_BUILD_ENABLE_ASAN=true ./build.sh
=> build: add asan build support

.github/workflows/centos_build.yaml, doc/build.md, lib/src/st_main.c, lib/src/st_mem.h, lib/src/st_tx_video_session.c, lib/src/st_util.c, tests/src/st20_test.cpp, tests/src/tests.cpp, tests/src/tests.h
=> test: fix mem leak

app/src/parse_json.c, lib/src/pipeline/st20_pipeline_rx.c, lib/src/pipeline/st20_pipeline_tx.c, lib/src/st_fmt.c, tests/src/st20p_test.cpp
=> st20p: support y210 input/output

app/sample/meson.build, app/sample/rx_rtp_video_sample.c, app/sample/rx_slice_video_sample.c, app/sample/rx_st20_pipeline_sample.c, app/sample/rx_st20_redundant_sample.c, app/sample/rx_st20_tx_st20_fwd.c, app/sample/rx_st20_tx_st20_split_fwd.c, app/sample/rx_st20p_tx_st20p_fwd.c, app/sample/rx_st20p_tx_st22p_fwd.c, app/sample/rx_st22_pipeline_sample.c, app/sample/rx_st22_video_sample.c, app/sample/rx_video_sample.c, app/sample/sample_util.c, app/sample/sample_util.h, app/sample/tx_rtp_video_sample.c, app/sample/tx_slice_video_sample.c, app/sample/tx_st20_pipeline_sample.c, app/sample/tx_st22_pipeline_sample.c, app/sample/tx_st22_video_sample.c, app/sample/tx_video_sample.c, app/sample/tx_video_split_sample.c, lib/src/st_sch.c, tests/script/sample_test.sh
=> sample: add args support

app/src/parse_json.c, app/tools/convert_app.c, app/tools/convert_app_args.c, app/tools/convert_app_base.h, include/st20_dpdk_api.h, include/st_convert_api.h, include/st_convert_internal.h, include/st_pipeline_api.h, lib/src/pipeline/st20_pipeline_rx.c, lib/src/pipeline/st20_pipeline_tx.c, lib/src/st_fmt.c, tests/src/cvt_test.cpp
This adds support for YCbCr 4:4:4 10 bits and RGB 10 bits.
=> Added support for 4:4:4 10 bits formats

app/src/app_base.h, app/src/tx_video_app.c, include/st20_dpdk_api.h, include/st20_redundant_api.h, include/st_dpdk_api.h, include/st_pipeline_api.h, lib/src/pipeline/st20_pipeline_rx.c, lib/src/pipeline/st20_pipeline_tx.c, lib/src/pipeline/st22_pipeline_rx.c, lib/src/pipeline/st22_pipeline_tx.c, lib/src/redundant/st20_redundant_rx.c, lib/src/st_rx_video_session.c, lib/src/st_tx_video_session.c, tests/src/st20p_test.cpp, tests/src/st22p_test.cpp, tests/src/tests.cpp, tests/src/tests.h
Move vsync to one st_event, also we can expand the event list to support more.
=> lib: add st_event

plugins/ffmpeg_plugin/0001-avdevice-kahawai-Add-the-kahawai-input-device-plugin.patch, plugins/ffmpeg_plugin/build_ffmpeg_plugin.sh, plugins/ffmpeg_plugin/ffmpeg_plugin.md, plugins/ffmpeg_plugin/kahawai.c
@jianxind @ricmli Please kindly review this.
=> sample: add the kahawai ffmpeg plugin

app/perf/meson.build, app/perf/p10le_to_rfc4175_422be10.c, app/perf/perf_dma.c, app/perf/perf_test.sh, app/perf/rfc4175_422be10_to_le.c, app/perf/rfc4175_422be10_to_le8.c, app/perf/rfc4175_422be10_to_p10le.c, app/perf/rfc4175_422be10_to_v210.c, app/perf/rfc4175_422be10_to_y210.c, app/perf/rfc4175_422le10_to_be.c, app/perf/v210_to_rfc4175_422be10.c, app/perf/y210_to_rfc4175_422be10.c, app/sample/dma_sample.c, app/sample/sample_util.c, app/sample/sample_util.h, lib/src/st_avx512.c, lib/src/st_fmt.c, lib/src/st_rx_video_session.c, plugins/sample/convert_plugin_sample.c
Usage:
./perf_prog --p_port 0000:af:01.0 --p_sip 192.168.89.89 --dma_port 0000:80:04.0
=> app/perf: support args

lib/src/pipeline/st20_pipeline_rx.c, tests/src/st20p_test.cpp
=> st20p/rx: fix and add sanity check for ext_frame

.github/workflows/ubuntu_build_skip_gtest.yml
=> ci: fix blocking PR checks when gtest skipped

.github/workflows/ubuntu_build_with_gtest.yml
=> ci: cancle previous running gtest after push in PR

app/sample/README.md
Signed-off-by: Han Qiang <qiang.han@intel.com>
=> Fix typo error in readme.

lib/src/pipeline/st20_pipeline_rx.c, tests/src/st20p_test.cpp
=> st20p: add more test for convert with line padding

.github/workflows/clang_build.yml, include/st_pipeline_api.h, lib/src/st2110/st_fmt.c, tests/src/st22p_test.cpp, tests/src/st_test.cpp
too many enum values in st_frame_fmt
=> pipeline/api: explicit declare the vaule of st_frame_fmt

doc/external_frame.md, include/st_pipeline_api.h
=> doc: introduce ext_frame api

lib/src/mt_arp.c, lib/src/mt_arp.h, lib/src/mt_dev.c, lib/src/mt_main.h, lib/src/mt_mcast.c
=> lib: cache arp results in a table

.github/workflows/windows.yml
=> ci/win: add tap build check

app/sample/sample_util.c, app/src/rxtx_app.c, include/mtl_api.h, lib/src/mt_arp.c, lib/src/mt_arp.h, lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_sch.c, lib/src/mt_socket.c, lib/src/mt_socket.h, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c
api: rename mtl_request_exit to mtl_abort
arp: add timeout option
tx_bust_busy: add timeout
=> dev: add timeout for arp and burst_busy

.github/workflows/centos_build.yaml, .github/workflows/clang_build.yml, .github/workflows/dpdk_patches_build.yml, .github/workflows/ubuntu_build.yml, .github/workflows/ubuntu_build_skip_gtest.yml, .github/workflows/ubuntu_build_with_gtest.yml, .github/workflows/windows.yml, doc/build_WIN.md, doc/run_WIN.md
this build add 8 min to the build time
=> ci: add ffmpeg plugin build

tests/src/cvt_test.cpp
=> test: add tests for st_convert API

include/st20_api.h, include/st_pipeline_api.h, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/st_rx_video_session.c, tests/src/st20p_test.cpp
=> st20p/rx: add packet level convert mode

lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c, tests/src/tests.cpp
suppress the error log in gtest
=> test: suppress the log level to error

CHANGELOG.md, lib/src/st2110/pipeline/st20_pipeline_tx.c, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_video_session.c
=> tx/video: check if addr in tranport for ext frame

lib/src/meson.build, lib/src/mt_dev.c, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_queue.h, lib/src/mt_stat.c, lib/src/mt_stat.h, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h
Enable in the udp dump.
Todo: migrate old static dump to this new ways.
=> stat: add runtime stat api

include/mtl_api.h, lib/src/mt_dev.c, lib/src/mt_main.c, lib/src/udp/udp_main.c
=> udp: fix sockaddr for mudp_recvfrom

plugins/ffmpeg_plugin/kahawai.c
=> plugins/ffmpeg: correct license notice

lib/src/mt_main.h, lib/src/mt_ptp.c
=> ptp: use coefficient to correct phc timestamp

lib/src/mt_main.h, lib/src/mt_ptp.c
=> ptp: use average coeffcient

lib/src/mt_ptp.c, lib/src/mt_socket.c, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/redundant/st20_redundant_rx.c, lib/src/udp/udp_main.c, tests/src/cvt_test.cpp
=> kw: fix klocwork issues

lib/src/mt_admin.c, lib/src/mt_util.c
=> sch: put old sch when migrating the session

app/udp/ufd_client.json, app/udp/ufd_client_sample.c, app/udp/ufd_server.json, app/udp/ufd_server_sample.c, lib/src/udp/ufd_main.c
also RTE_FINI(mufd_finish) for the lib destructor.
cfg support set queues/socket max nb.
=> ufd: add poll support.

lib/src/mt_main.h, lib/src/mt_ptp.c
=> ptp: print mean path delay

.github/workflows/ubuntu_build_with_gtest.yml
=> CI: clean the running gtest if.

include/mudp_api.h, include/mudp_sockfd_api.h, lib/src/mt_platform.h, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, lib/src/udp/ufd_main.c
=> udp: add getsockopt/setsockopt/fcntl support.

app/sample/sample_util.c, app/sample/sample_util.h, app/udp/udp_client_sample.c, app/udp/udp_server_sample.c, include/mtl_api.h, lib/src/meson.build, lib/src/mt_cni.c, lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_rss.c, lib/src/mt_rss.h, lib/src/mt_stat.c, lib/src/mt_util.c, lib/src/mt_util.h, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h
usage:
./build/app/UdpClientSample --rss
./build/app/UdpServerSample --rss
=> rss: enable udp rx with rss support.

lib/src/mt_dev.c, lib/src/mt_main.h, lib/src/mt_rss.c
pf is working, not know why vf has different hash value.
=> rss: add l4 support

lib/src/mt_dev.c, lib/src/mt_main.c
=> dev: fix panic with error exit

app/src/args.c, include/mtl_api.h, lib/src/mt_main.h, lib/src/mt_ptp.c
The gains KP and KI need further tuning.
=> ptp: use pi controller to fine tune the coefficient

lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_shared_queue.c, lib/src/mt_shared_queue.h, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h
usage:
./build/app/UdpServerSample --shared_queues --sessions_cnt 4 --queues_cnt 2
./build/app/UdpClientSample --shared_queues --sessions_cnt 4 --queues_cnt 2
=> sq: add tx support

.github/workflows/ubuntu_build_with_gtest.yml, doc/build.md, doc/experimental/header_split.md, docker/Dockerfile, script/build_dpdk.sh
=> dpdk: upgrade to 22.11

app/udp/ufd_client.json, app/udp/ufd_server.json, lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_shared_queue.c, lib/src/mt_shared_queue.h, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, lib/src/udp/ufd_main.c, lib/src/udp/ufd_main.h
=> ufd: add tx bps config support

app/meson.build, app/sample/README.md, app/sample/meson.build, app/sample/rx_st20p_tx_st20p_downsample_fwd.c
=> sample: add 4k to 1080p downsample forward

include/mudp_api.h, include/mudp_sockfd_api.h, lib/src/mt_shared_queue.c, lib/src/udp/udp_main.c, lib/src/udp/ufd_main.c, lib/src/udp/ufd_main.h
=> ufd: add pcie port support

app/sample/rx_st20p_tx_st20p_downsample_fwd.c, include/st_pipeline_api.h, lib/src/st2110/st_avx512_vbmi.c, lib/src/st2110/st_avx512_vbmi.h, lib/src/st2110/st_convert.c
=> cvt: add half downsample and vbmi version

app/sample/rx_st20p_tx_st20p_downsample_fwd.c, include/st_pipeline_api.h, lib/src/st2110/st_convert.c
=> cvt: add idx to downsample for 2si cases

app/udp/udp_client_sample.c, app/udp/udp_server_sample.c, app/udp/ufd_client_sample.c, app/udp/ufd_server_sample.c, include/mudp_api.h, lib/src/mt_dev.c, lib/src/mt_main.h, lib/src/mt_ptp.c, lib/src/mt_shared_queue.c, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h
=> udp: add SO_RCVTIMEO support

CODEOWNERS
=> CODEOWNERS: first version

app/udp/udp_client_sample.c, app/udp/udp_server_sample.c, app/udp/udp_test.sh, app/udp/ufd_client.json, app/udp/ufd_client_sample.c, app/udp/ufd_server.json, app/udp/ufd_server_sample.c, app/udp/usocket_client_sample.c, app/udp/usocket_server_sample.c, lib/src/mt_cni.c, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h
=> udp: add default bind port

app/meson.build, app/sample/meson.build, app/sample/rx_st20_tx_st20_split_fwd.c, app/sample/rx_st20p_tx_st20p_downsample_fwd.c, app/sample/rx_st20p_tx_st20p_split_fwd.c, doc/dma.md
TODO before merge: add the st20p split forward
=> sample: add st20p split forward

app/meson.build, app/sample/README.md, app/sample/meson.build, app/sample/rx_st20p_tx_st20p_merge_fwd.c, app/sample/rx_st20p_tx_st20p_split_fwd.c
=> sample: add st20p merge forward

CHANGELOG.md, README.md, app/udp/README.md
=> udp: add the doc

app/udp/ufd_client_sample.c, app/udp/ufd_server_sample.c, include/mtl_api.h, include/mudp_sockfd_api.h, lib/src/udp/ufd_main.c
=> ufd: support override config for debug usage

.github/workflows/windows.yml, app/meson.build
App build is broken for win actually.
=> CI/win: not use same step for app and test

.github/workflows/ubuntu_build_with_gtest.yml, format-coding.sh, lib/src/udp/udp_main.c, lib/src/udp/ufd_main.c, tests/meson.build, tests/src/meson.build, tests/src/test_platform.h, tests/src/test_util.cpp, tests/src/test_util.h, tests/src/tests.cpp, tests/src/tests.h, tests/src/ufd_loop_test.cpp, tests/src/ufd_test.cpp, tests/src/ufd_test.h
usage:
./build/tests/KahawaiUfdTest --p_port 0000:af:01.0 --r_port 0000:af:01.1
shared queue mode:
./build/tests/KahawaiUfdTest --p_port 0000:af:01.0 --r_port 0000:af:01.1 --queue_mode shared
=> test: first ufd test routine

include/mudp_sockfd_internal.h, lib/src/mt_main.h, lib/src/mt_shared_queue.c, lib/src/mt_shared_queue.h, lib/src/udp/udp_main.c, lib/src/udp/ufd_main.c, tests/src/ufd_loop_test.cpp
also shared mempool for shared queue since mempool nb is limited
=> test/ufd: add dual_loop and shared_max case

lib/src/mt_dev.c, tests/src/ufd_loop_test.cpp, tests/src/ufd_test.cpp, tests/src/ufd_test.h
Cover SO_SNDBUF/SO_RCVBUF/SO_RCVTIMEO/IP_ADD_MEMBERSHIP/IP_DROP_MEMBERSHIP
=> test/ufd: add socketopt test

lib/src/mt_dev.c, lib/src/udp/udp_main.c, tests/meson.build, tests/src/test_platform.h, tests/src/ufd_loop_test.cpp
=> test/ufd: add poll test

script/nicctl.sh
=> script/nicctl: use Grouping Commands to avoid grep error

lib/src/mt_arp.c, lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_main.h, lib/src/mt_shared_queue.c, lib/src/mt_socket.c, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, lib/src/udp/ufd_main.c, tests/src/ufd_test.cpp
udp: report tx succ if arp is not resloved.
arp: use timer task to track the arp status.
=> arp: use timer task to track the arp status

lib/src/mt_dev.c, lib/src/mt_tap.c, lib/src/mt_util.h
clear rte_tm_error to zero to avoid dirty data
=> dev/rl: fix panic when rl commit fail.

.github/workflows/ubuntu_build_with_gtest.yml, CHANGELOG.md, app/sample/sample_util.c, app/sample/sample_util.h, app/udp/udp_test.sh, app/udp/ufd_client.json, app/udp/ufd_client_sample.c, app/udp/ufd_server.json, app/udp/ufd_server_sample.c, include/mtl_api.h, include/mudp_sockfd_api.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_sch.c, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, lib/src/udp/ufd_main.c, tests/script/ufd_gtest.sh, tests/src/ufd_test.cpp
reduce core usage if app call poll for each fd, "--udp_lcore" to enable.
sch/tasklet: add runtime unregister support.
=> udp: add lcore mode for rx

.github/workflows/ubuntu_build_with_gtest.yml, app/src/args.c, doc/build.md, doc/build_WIN.md, doc/run.md, include/mtl_api.h, lib/src/mt_dev.c, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_rss.c, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, patches/dpdk/22.11/0007-net-iavf-not-include-ipv4_port-for-RTE_ETH_RSS_NONFR.patch, tests/script/st2110_test.sh, tests/src/st20p_test.cpp, tests/src/st40_test.cpp, tests/src/st_test.cpp, tests/src/tests.cpp
also rename l4 udp name to MT_RSS_MODE_L4_UDP.
=> iavf: fix rss udp l4

app/meson.build, app/sample/ext_frame/rx_st20p_hdr_split_gpu_direct.c, app/sample/meson.build, app/sample/sample_util.c, app/sample/sample_util.h, doc/external_frame.md, include/mtl_api.h, include/st_pipeline_api.h, lib/src/mt_dev.c, lib/src/mt_main.c, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/st_rx_video_session.c
sudo ./build/app/RxSt20pHdrSplitGpuDirect --p_port 0000:18:00.0 --udp_port 6970 --gddr_pa 0x390200000000
For tx, pls use udp port 6970 since current DDP only support hdr split on 6970
./build/app/TxSt20PipelineSample --udp_port 6970
=> sample: add hdr split with gpu direct

app/udp/udp_client_sample.c, app/udp/udp_server_sample.c, app/udp/ufd_client_sample.c, app/udp/ufd_server_sample.c, include/meson.build, include/mtl_api.h, include/mudp_api.h, include/mudp_sockfd_api.h, include/mudp_sockfd_internal.h, include/mudp_win.h, ld_preload/udp/udp_preload.c, ld_preload/udp/udp_preload.h, lib/src/mt_dev.c, lib/src/mt_shared_queue.c, lib/src/st2110/st_header.h, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, lib/src/udp/ufd_main.c, lib/src/udp/ufd_main.h
udp: add sendmsg/recvmsg/select support 
upl: return kfd for socket api
udp: return -1 for the API, and set errno to the cause
=> Udp: add sendmsg/recvmsg/select support

ld_preload/udp/udp_preload.c, lib/src/udp/udp_main.c, lib/src/udp/ufd_main.c
default set to zero timeout for rx and arp
=> udp: default rx timeout to zero

app/meson.build, ld_preload/udp/meson.build, lib/meson.build, plugins/meson.build, plugins/st22_ffmpeg/meson.build, tests/meson.build
Debug build should disable Werror for continues develop.
=> build: disable Werror for debug build

include/mtl_api.h, include/mudp_api.h, include/mudp_win.h, lib/src/mt_platform.h, lib/src/mt_shared_queue.c, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h
Support Generic Segmentation Offload feature.
=> udp: add gso support

ld_preload/udp/udp_preload.c, tests/src/upl_loop_test.cpp
Also fix panic if upl_epoll_close with ufd open
=> upl/test: add select, epoll, mix_fd case

app/sample/ext_frame/rx_st20p_hdr_split_gpu_direct.c, app/sample/sample_util.c, app/sample/sample_util.h
usage:
./build/app/TxSt20PipelineSample --p_sip 192.168.70.12 --p_tx_ip 239.168.70.100  --p_port 0000:af:01.0 --udp_port 6971
sudo ./build/app/RxSt20pHdrSplitGpuDirect --p_sip 192.168.70.13 --p_rx_ip 239.168.70.100 --p_port 0000:18:00.0  --udp_port 6971 --gddr_pa 0x390200000000 --use_cpu_copy
=> sample/gpu_direct: add cpu copy to gpu for benchmark test

include/st30_api.h, lib/src/mt_main.c, lib/src/mt_main.h, tests/src/test_util.h, tests/src/tests.cpp
ptp read is an expensive mmio read operation
=> ptp: add cache read support for user api

app/src/app_base.h, app/src/tx_ancillary_app.c, app/src/tx_audio_app.c, app/src/tx_video_app.c, include/st20_api.h, include/st30_api.h, include/st40_api.h, include/st_api.h, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c
tx/st20: add epoch in st20_tx_frame_meta
tx/audio: add epoch in st30_tx_frame_meta
tx/anc: add epoch in st40_tx_frame_meta
=> tx/st2110: add epoch in stxx_tx_frame_meta

lib/src/mt_dev.c, lib/src/st2110/st_fmt.c, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c, lib/src/udp/ufd_main.c, tests/src/ufd_test.cpp
tx/video: remove unnecessary has_inflight
tx/audio: remove unnecessary has_inflight
tx/anc: remove unnecessary has_inflight
=> tx/st2110: remove unnecessary has_inflight

.github/workflows/msys2_build.yml, CHANGELOG.md, doc/build_WIN_MSYS2.md, patches/dpdk/23.03/windows/0001-Add-DDP-package-load-support-in-windows.patch, patches/dpdk/23.03/windows/0002-Change-list-remove-and-add-position-to-avoid-race-co.patch, patches/dpdk/23.03/windows/0003-Mingw-compiler-do-have-same-implementation.patch, patches/dpdk/23.03/windows/0004-Mingw-do-have-pthread-implementation-change-to-adapt.patch, patches/dpdk/23.03/windows/0005-To-change-for-windows-trained-pad_interval-pass.patch, patches/dpdk/23.03/windows/0006-Enable-descriptor-prefetch-for-CBDMA-version-3.4.patch, patches/dpdk/23.03/windows/0007-Windows-need-set-the-timer-resolution-to-maximum-to-.patch, patches/dpdk/23.03/windows/0008-Windows-dsa-driver-need-set-to-reset-status-first.patch, patches/dpdk/23.03/windows/0009-Windows-version-currently-no-BPF-support.patch, patches/dpdk/23.03/windows/0010-Remove-affinity-binding-for-windows-will-have.patch, patches/dpdk/23.03/windows/0011-Fix-list-dir-glob-expassion-in-msys2.patch, patches/dpdk/23.03/windows/0012-Use-alarm-to-workaround-vf-uio-no-intr-issue.patch, patches/dpdk/23.03/windows/0013-Temporarily-disable-pcapng-build.patch
Windows doc/ci update to 23.03 version too
Remove 1GB page patch since IMTL works with 2MB page now
Update changelog
=> dpdk: add 23.03 support for windows

README.md
=> badge: add OpenSSF Scorecard

README.md, doc/asan.md, doc/build.md, doc/convert.md, doc/dma.md, doc/experimental/af_xdp.md, doc/experimental/header_split.md, doc/external_frame.md, doc/plugin.md, doc/run.md, doc/run_WIN.md, doc/udp.md
=> doc: add codeql and dependabot badge

lib/src/udp/meson.build, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, lib/src/udp/udp_rxq.c, lib/src/udp/udp_rxq.h
=> udp: split rx logical

app/src/args.c, doc/run.md, include/mtl_api.h, lib/src/st2110/st_tx_video_session.c, lib/src/st2110/st_video_transmitter.c
no warm_pkts for tsc pacing, --pacing_way tsc_narrow
=> pacing/tsc: remove warm_pkts and add tsc_narrow

lib/src/st2110/st_tx_video_session.c
first field align to even epoch
=> tx/pacing: interlaced should align second field to odd epoch

ecosystem/ffmpeg_plugin/kahawai_dec.c
This PR adds RGB24 pix_fmt support to kahawai demuxer
=> add rgb24 support to kahawai_dec ffmpeg plugin

lib/src/mt_main.c, lib/src/mt_main.h, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, lib/src/udp/udp_rxq.c, lib/src/udp/udp_rxq.h
queue can be shared for clients with reuse port enabled.
=> udp/rxq: use client and queue struct

lib/src/mt_dev.c
rte_eal_init will pin the thread to main lcore
=> dev: init eal in one thread

lib/src/st2110/st_header.h, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_tx_audio_session.c
Report mismatch error if the pkt payload size not euqal the expected.
=> rx/audio: add pkt len check

include/mudp_sockfd_internal.h, ld_preload/udp/udp_preload.c, ld_preload/udp/udp_preload.h, lib/src/udp/ufd_main.c
Register the fork use pthread_atfork, also move all memory alloc to rte_based that it can be shared between process.
=> upl: add child fork path

app/sample/rx_st20_pipeline_sample.c, app/sample/rx_st22_pipeline_sample.c
only dump yuv to file if "--rx_dump" is provided.
=> sample/st22p: use "--rx_dump" to control the yuv dump

.github/workflows/msys2_build.yml
Change msys2_build to reusable workflow consume by other workflows.
* Improve on IMTL quality release to generate functional libs, apps, plugins to be consume
* Build matrix to deliver quality metrices
* Enable reuse workflow to be integrated with other user workflows with use "libmtl"
=> msys2: Add build strategy matrix to include IMTL and DPDK release

lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/st_rx_video_session.c, tests/src/dma_test.cpp, tests/src/st20p_test.cpp, tests/src/st22p_test.cpp, tests/src/st_test.cpp, tests/src/tests.cpp, tests/src/tests.h
test: get rss mode from imtl
test: skip ext and dma if pa mode
st20/rx: fix quota on srss
=> test: fix gtest on instance with PA and SRSS mode

ld_preload/udp/udp_preload.c
Some libc function called before upl_init..
=> udp/preload: fix unresolved libc_fn

lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_main.h, lib/src/mt_queue.c, lib/src/mt_queue.h, lib/src/mt_shared_queue.c, lib/src/mt_shared_queue.h, lib/src/st2110/st_ancillary_transmitter.c, lib/src/st2110/st_audio_transmitter.c, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c, lib/src/st2110/st_video_transmitter.c, lib/src/udp/udp_main.c, lib/src/udp/udp_main.h, tests/src/st22_test.cpp, tests/src/st30_test.cpp, tests/src/st40_test.cpp
mt_txq_get will call the real path according to the settings
=> tx: use mt_txq_get for all tx queue request

.github/workflows/msys2_build.yml, lib/src/mt_main.h, lib/src/mt_tap.c
=> CI: msys2_build should not bind to main only

lib/src/mt_util.h, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_audio_session.c
Address the problem of rte rings exceeding the RTE_MAX_MEMZONE threshold.
=> st30/tx: replace trans ring with fifo

lib/src/mt_cni.c, lib/src/mt_main.h, lib/src/mt_ptp.c, lib/src/mt_ptp.h
to get the input udp stream info of the instance
=> cni: add udp stream info for debug usage

app/sample/sample_util.c
./build/app/TxSt20PipelineSample --payload_type 113 
./build/app/RxSt20PipelineSample --payload_type 113
=> sample: add --payload_type args

app/sample/fwd/rx_st20_tx_st20_split_fwd.c, app/sample/fwd/rx_st20p_tx_st20p_downsample_merge_fwd.c, app/sample/fwd/rx_st20p_tx_st20p_merge_fwd.c, app/sample/fwd/rx_st20p_tx_st20p_split_fwd.c, app/sample/msvc/imtl_sample/imtl_sample.cpp, app/sample/sample_util.c, app/sample/sample_util.h, app/sample/tx_video_split_sample.c, app/src/app_base.h, app/src/rxtx_app.c, doc/doxygen/programmers_guide.md, ecosystem/ffmpeg_plugin/kahawai_common.c, ecosystem/msdk/0001-add-imtl-support-in-sample_encode.patch, ecosystem/obs_mtl/linux-mtl/mtl-input.c, ecosystem/obs_mtl/linux-mtl/mtl-output.c, include/mtl_api.h, include/st_api.h, lib/src/mt_dev.c, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/udp/ufd_main.c, tests/script/loop_json/audio_128v.json, tests/src/st_test.cpp, tests/src/tests.cpp, tests/src/ufd_test.cpp
tx_sessions_cnt_max/rx_sessions_cnt_max is deprecated
=> api: use tx_queues_cnt/rx_queues_cnt

lib/src/mt_cni.c, lib/src/mt_main.h, lib/src/mt_queue.c, lib/src/mt_shared_rss.c, lib/src/mt_shared_rss.h, lib/src/mt_util.h, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, lib/src/udp/udp_rxq.c
mt_srss_burst dequeue from ring, srss tasklet enqueue to ring.
And delete the rss code in rv video.
=> srss: add mt_srss_burst support by ring

lib/src/st2110/st_tx_video_session.c
to get more accurate frame time
=> video/pacing: align the pkt profiling to nic tx_free_thresh

lib/src/st2110/st_video_transmitter.c
easy to add action on the pkt tx
=> tx/video: unify the tx burst into one place

app/src/rx_video_app.c, lib/src/mt_rtcp.c, lib/src/mt_rtcp.h
=> rtcp/rx: ignore out of range or exceed nack

app/src/app_base.h, app/src/rxtx_app.c, include/mtl_api.h, include/st_api.h, lib/src/mt_dev.c, lib/src/mt_main.c, lib/src/mt_main.h, tests/src/dma_test.cpp, tests/src/st20_test.cpp, tests/src/st20p_test.cpp, tests/src/st22_test.cpp, tests/src/st22p_test.cpp, tests/src/st30_test.cpp, tests/src/st40_test.cpp, tests/src/st_test.cpp
also move st related to st_get_var_info
=> api: move stat/cap to fix_info and var_info

doc/run.md
(cherry picked from commit cbd833df2142a2fabc23f8ad2e79654ee58cab8c)
=> doc: fix chown command (#391)

lib/src/st2110/st_tx_video_session.c, tests/src/st20_test.cpp
test: check meta_timing only if fps check is true
test: no fps check for detect_uframe_mix_s2
tx/video: fix user_meta ipv4 hdr
=> test: fix the test on aws

lib/src/mt_cni.c, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_tx_video_session.c, lib/src/st2110/st_video_transmitter.c
=> tx/video: use ptp time as time source of warm up

ecosystem/ffmpeg_plugin/kahawai_common.c
Added
MTL_FLAG_TX_VIDEO_MIGRATE
MTL_FLAG_RX_VIDEO_MIGRATE
MTL_FLAG_RX_SEPARATE_VIDEO_LCORE
=> Add rx tx load balancing flags

.gitignore, doc/run.md, script/status_report.sh
dmesg, cmdline, hugepage, dpdk, driver, lspci etc
=> script: add status_report script to collect all system info

ecosystem/ffmpeg_plugin/README.md
The udp_port of the RxTxApp will increment by two when operating in replica mode.
=> ecosystem/ffmpeg: doc for udp_port increment by 2

app/src/rx_st20p_app.c, app/src/rx_video_app.c, app/src/tx_st20p_app.c, app/src/tx_video_app.c, doc/run.md, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_video_session.c, lib/src/st2110/st_video_transmitter.c, script/status_report.sh
session create may take a long time(> 10s)
=> app: check handle before get io status

app/sample/sample_util.c, app/sample/sample_util.h, doc/experimental/af_xdp.md, include/st_api.h, lib/src/mt_cni.c, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_socket.c, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, lib/src/udp/ufd_main.c, script/nicctl.sh, tests/script/afxdp_json/1080p59_1v.json, tests/script/afxdp_json/mix_port.json, tests/script/afxdp_json/mix_port2.json, tests/script/afxdp_json/multicast_1v_1a_1anc.json, tests/script/afxdp_json/multicast_redundant_1v_1a_1anc.json, tests/script/afxdp_json/rtp_1080p59_1v.json, tests/script/afxdp_json/rtp_multicast_1v_1a_1anc.json, tests/script/afxdp_json/rtp_redundant_1v_1a_1anc.json, tests/script/afxdp_json/setup.sh, tests/script/afxdp_json/ufd_client.json, tests/script/afxdp_json/ufd_server.json, tests/script/afxdp_json/unicast_1080p59_1v.json, tests/src/st20_test.cpp, tests/src/st22_test.cpp
usage:
MUFD_CFG=tests/script/afxdp_json/ufd_client.json ./build/app/UfdClientSample --p_tx_ip 192.168.108.101
MUFD_CFG=tests/script/afxdp_json/ufd_server.json ./build/app/UfdServerSample
=> afxdp: add udp transport support.

include/mtl_api.h, lib/src/mt_main.c, tests/src/tests.cpp
mtl_set_log_level and mtl_get_log_level
=> api: add runtime log level api

README.md, app/src/app_base.h, app/src/args.c, app/src/tx_st20p_app.c, app/src/tx_st22_app.c, app/src/tx_st22p_app.c, app/src/tx_video_app.c, include/st20_api.h, include/st30_api.h, include/st40_api.h, include/st_pipeline_api.h, lib/src/st2110/pipeline/st20_pipeline_tx.c, lib/src/st2110/pipeline/st22_pipeline_tx.c, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_tx_video_session.c
Fix the no slot log for redundant path.
Also add no_bulk flag support.
=> rx/video: detect the last drop pkt of redundant.

.github/workflows/msys2_build.yml, .github/workflows/msys2_ffmpeg.yml, .github/workflows/ubuntu_build_skip_gtest.yml, .github/workflows/windows_build_with_gtest.yml, ecosystem/ffmpeg_plugin/build_ffmpeg_plugin.sh, lib/src/mt_main.c, tests/src/dma_test.cpp, tests/src/st_test.cpp
1. add gtest for windows self-hosted
2. add cache for DPDK windows build
=> CI: add windows gtest

.gitignore, lib/src/meson.build, lib/src/mt_arp.c, lib/src/mt_arp.h, lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_flow.c, lib/src/mt_flow.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_shared_queue.c
=> flow: move flow code to mt_flow.c

include/mtl_api.h, lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_flow.c, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_socket.c, lib/src/mt_socket.h, lib/src/mt_util.c, lib/src/mt_util.h, lib/src/st2110/st_ancillary_transmitter.c, lib/src/st2110/st_audio_transmitter.c, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, tests/script/af_packet_json/1080p59_1v.json, tests/script/af_packet_json/multicast_1v_1a_1anc.json, tests/script/af_packet_json/st22p_1v_1080p59.json
also allocate audio/anc TX queue for port on demand.
=> af_pkt: force to shared rx queue mode

lib/src/mt_dev.c, lib/src/mt_dev.h, lib/src/mt_flow.c, lib/src/mt_main.h, lib/src/mt_queue.c, lib/src/mt_queue.h, tests/script/kernel_socket_json/1080p59_1v.json
also add placeholder for kernel based queue
=> queue: use function pointer for tx/rx burst

.github/workflows/msys2_build.yml, .github/workflows/windows_build_with_gtest.yml, action.yml, app/meson.build, doc/build_WIN.md, ecosystem/obs_mtl/linux-mtl/meson.build, ld_preload/meson.build, lib/meson.build, meson.build, patches/dpdk/23.07/windows/0010-Fix-list-dir-glob-expassion-in-msys2.patch, plugins/meson.build, plugins/st22_ffmpeg/meson.build, tests/meson.build
There are bugs with pkg-config in mingw environment, replace it with pkgconf since the latter has more feature.
=> win: replace pkg-config with pkgconf

lib/src/datapath/mt_dp_socket.c, lib/src/datapath/mt_queue.c, lib/src/dev/mt_dev.c, lib/src/mt_cni.c, lib/src/mt_main.h, lib/src/mt_ptp.c, lib/src/mt_util.c, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c
test with sudo ./build/app/RxTxApp --config_file tests/script/kernel_socket_json/rx.json --ptp
=> ptp: add support without cni

lib/src/datapath/mt_dp_socket.c, lib/src/datapath/mt_queue.c, lib/src/datapath/mt_shared_queue.c, lib/src/datapath/mt_shared_rss.c, lib/src/dev/mt_dev.c, lib/src/mt_cni.c, lib/src/mt_flow.c, lib/src/mt_main.h, lib/src/mt_ptp.c, lib/src/mt_socket.c, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_tx_video_session.c, lib/src/udp/udp_rxq.c
Use MT_TXQ_FLOW_F_FORCE_SOCKET/MT_RXQ_FLOW_F_FORCE_SOCKET to select socket path for the queue.
test with:
sudo ./build/app/RxTxApp --config_file tests/script/dpdk_af_xdp_json/rx.json --ptp
=> datapath/queue: add force socket option support

lib/src/datapath/mt_dp_socket.c, lib/src/datapath/mt_dp_socket.h, lib/src/mt_main.h, lib/src/mt_util.h, plugins/st22_ffmpeg/README.md
one socket is only capable to handle 4g bit per second traffic.
=> dp/socket: add multi thread for tx

app/src/app_base.h, app/src/app_platform.h, app/src/args.c, app/src/rxtx_app.c, doc/run.md, include/mtl_api.h, lib/src/mt_main.c, lib/src/mt_ptp.c
app can use this notify for some related monitor task.
=> ptp: add sync notify callback

lib/src/dev/mt_dev.c, lib/src/mt_arp.c, lib/src/mt_dhcp.c, lib/src/mt_main.h, lib/src/mt_mcast.c, lib/src/mt_ptp.c, lib/src/mt_rtcp.c, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c, patches/dpdk/23.07/0006-e810-set-max-ring-desc-to-8160-which-e810-max-allowe.patch
Fix ptp mbuf alloc fail with "--ptp --nb_tx_desc 4096"
=> inf: set tx sys mem pool size to (nb_tx_desc + 1024)

.github/workflows/ubuntu_build_with_gtest.yml, include/mtl_api.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/st2110/st_rx_video_session.c, tests/src/st20_test.cpp, tests/src/st20p_test.cpp, tests/src/st22_test.cpp, tests/src/st30_test.cpp, tests/src/st40_test.cpp, tests/src/tests.cpp, tests/src/tests.h
test with:
./build/tests/KahawaiTest --p_port kernel:lo --r_port kernel:lo --auto_start_stop
=> dp/socket: fix for gtest

tools/ebpf/Makefile, tools/ebpf/README.md, tools/ebpf/et.c, tools/ebpf/et.h, tools/ebpf/fentry.bpf.c
The first tool is for tracing udp_send_skb calls.
=> tools: add ebpf_tools

CHANGELOG.md, app/src/args.c, doc/run.md, include/mtl_api.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c
And it can be customized by "--arp_timeout_s <sec>"
=> arp: set default arp timeout to 60s

doc/run.md, lib/src/dev/mt_af_xdp.c, lib/src/dev/mt_af_xdp.h, script/if_filter_delete.sh, tests/src/st20_test.cpp, tests/src/tests.cpp
test with: ./build/tests/KahawaiTest --p_port native_af_xdp:enp0s3np0 --r_port native_af_xdp:enp0s4np0 --queue_cnt=8 --start_queue 3
=> tests: add --queue_cnt to set the queues number for port

lib/src/datapath/mt_queue.c, lib/src/datapath/mt_shared_queue.c, lib/src/dev/mt_af_xdp.c, lib/src/dev/mt_af_xdp.h, lib/src/mt_main.h, tests/script/native_af_xdp_json/loop.json, tests/script/native_af_xdp_json/loop_4k.json, tests/script/native_af_xdp_json/loop_rtp.json, tests/script/native_af_xdp_json/loop_shared.json, tests/script/native_af_xdp_json/mcast.json, tests/script/native_af_xdp_json/redundant.json, tests/script/native_af_xdp_json/st22p.json, tests/script/native_af_xdp_json/st22p_redundant.json
test with:
./build/app/RxTxApp --config_file tests/script/native_af_xdp_json/loop_shared.json --video_sha_check
=> shared_queue: add both dpdk and xdp support

doc/run.md, script/nicctl.sh
=> script/nicctl: add create_tvf command

lib/src/mt_platform.h, lib/src/mt_socket.c
Replace external cmd calling with code.
1. dp/socket: add/remove flow with ioctl
2. dp/socket: get gateway from route file
=> dp/socket: add/remove flow with ioctl

lib/src/dev/mt_af_xdp.c, lib/src/dev/mt_af_xdp.h, tools/ebpf/Makefile, tools/ebpf/README.md, tools/ebpf/et.c, tools/ebpf/et.h, tools/ebpf/xsk.xdp.c
Add a custom xdp kernel program to filter udp4 dest port.
Usage: 
cd tools/ebpf && make
sudo ./et --prog xdp --ifname ens785f0,ens785f1 --xdp_path xsk.xdp.o
=> tools/ebpf: add udp4 dest port filter for xdp

docker/README.md, docker/ubuntu.dockerfile, lib/src/mt_sch.c
Use shared IPC option `--ipc=host` for the docker run command
=> docker: add multiple docker containers support

lib/meson.build, lib/src/dev/mt_af_xdp.c, lib/src/st2110/st_tx_video_session.c
add xdp_tx_wakeup if xsk_ring_prod__reserve fail, also add copy mode detect.
=> xdp: fix tx stop with copy mode

.github/workflows/upstream_sync.yml, build.sh
Fix Ubuntu 20.04 compatibility.
=> build: revert meson command change

.github/workflows/upstream_sync.yml, build.sh
Fix Ubuntu 20.04 compatibility.
---------
=> build: revert meson command change (#597)

lib/src/dev/mt_af_xdp.c, lib/src/dev/mt_af_xdp.h, manager/mtl_instance.hpp, manager/mtl_manager.cpp, tools/ebpf/README.md, tools/ebpf/et.c, tools/ebpf/et.h
This function is integrated to MTL Manager.
=> tools/ebpf: remove xsk_map_fd send function

lib/src/dev/mt_af_xdp.c, lib/src/dev/mt_af_xdp.h, manager/mtl_instance.hpp, manager/mtl_manager.cpp, tools/ebpf/README.md, tools/ebpf/et.c, tools/ebpf/et.h
This function is integrated to MTL Manager.
---------
=> tools/ebpf: remove xsk_map_fd send function (#610)

lib/src/datapath/mt_queue.c, lib/src/datapath/mt_shared_queue.c, lib/src/dev/mt_dev.c, lib/src/mt_admin.c, lib/src/mt_cni.c, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_ptp.c, lib/src/mt_sch.c, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c, lib/src/udp/udp_rxq.c
indicate the api return is determined from user input
=> mt: refine the user para api to mt_user_*

include/mtl_api.h, include/st20_api.h, include/st_api.h, include/st_pipeline_api.h, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/st_fmt.c, python/example/st20p_rx.py, python/swig/pymtl.i
test with:
./build/app/TxSt20PipelineSample
python3 python/example/st20p_rx.py
=> python: add st20p_rx support

.gitignore, README.md, format-coding.sh, include/st_pipeline_api.h, lib/src/st2110/st_fmt.c, python/README.md, python/example/cv2_util.py, python/example/st20p_rx.py
move all cv2 code to cv2_util.py
=> python/st20p_rx: add more format support

app/src/player.c
display freeze with debug build, backtrace shows block on audio part, remove it.
also use some init sequence for both windows and linux.
#0  __futex_abstimed_wait_common (cancel=false, private=0, abstime=0x0, clockid=0, expected=2, futex_word=0x7f40d1e1aca8 <_nl_state_lock+8>) at ./nptl/futex-internal.c:103
#1  __GI___futex_abstimed_wait64 (futex_word=futex_word@entry=0x7f40d1e1aca8 <_nl_state_lock+8>, expected=expected@entry=2, clockid=clockid@entry=0, abstime=abstime@entry=0x0,
private=private@entry=0) at ./nptl/futex-internal.c:128
#2  0x00007f40d1c9b315 in __pthread_rwlock_wrlock_full64 (abstime=0x0, clockid=0, rwlock=0x7f40d1e1aca0 <_nl_state_lock>) at ./nptl/pthread_rwlock_common.c:829
#3  ___pthread_rwlock_wrlock (rwlock=rwlock@entry=0x7f40d1e1aca0 <_nl_state_lock>) at …
=> app/sdl: remove SDL_INIT_AUDIO

app/v4l2_to_ip/v4l2_to_ip.c
Add fault detection at caller side because the error message has been removed.
(cherry picked from commit d4268eb4a0744d6e6998742c6c62bdaad6fdc2f7)
=> app/v4l2_to_ip: add fault detection (#659)

.dockerignore, docker/README.md, docker/docker-compose.yml, docker/ubuntu.dockerfile, manager/.dockerignore, manager/Dockerfile, manager/meson.build
1. use local source files
2. use multi-stage build to reduce image size
=> docker: use local source files

lib/src/mt_admin.c, lib/src/mt_main.h, lib/src/mt_sch.c, lib/src/mt_sch.h, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_rx_video_session.h, lib/src/st2110/st_tx_video_session.c, lib/src/st2110/st_tx_video_session.h, lib/src/st2110/st_video_transmitter.c, python/example/st20p_tx_decode.py
As it provides more accurate results than the NIC statistics method.
=> admin: calculate CPU utilization based on average tasklet loop time

app/src/app_base.h, app/src/args.c, app/src/player.c, app/src/rx_st20p_app.c, app/src/rx_st20r_app.c, app/src/rx_st22p_app.c, app/src/rx_video_app.c, app/src/rxtx_app.c, app/src/tx_st20p_app.c, app/src/tx_st22p_app.c, app/src/tx_video_app.c, tests/script/loop_json/1080i59_1v.json, tests/script/loop_json/st20p_1v_1080i50.json, tests/script/loop_json/st20p_1v_1080p59.json
test with:
./build/app/RxTxApp --config_file
tests/script/loop_json/st20p_1v_1080i50.json --p_port 0000:ac:01.1 --r_port 0000:ac:01.0 --rx_display
=> app/display: fix interlace support

doc/experimental/header_split.md, lib/src/st2110/st_rx_video_session.c
(cherry picked from commit 196864ac60c558518aef05e8919111b07295cb45)
=> hdr_split: fix null slot frame addr

app/v4l2_to_ip/v4l2_to_ip.c
obfuscate the code order to prevent similar code pattern.
=> app/v4l2_to_ip: fix license compliance issue.

app/v4l2_to_ip/v4l2_to_ip.c
(cherry picked from commit f4a85c5e7af8e0965a1010755d94df84d70293ac)
=> app/v4l2_to_ip: refine code

CHANGELOG.md, app/src/parse_json.c, app/src/parse_json.h, app/src/rx_ancillary_app.c, app/src/tx_ancillary_app.c, doc/design.md, include/st40_api.h, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_tx_ancillary_session.c, tests/script/loop_json/unicast_interlaced_1anc.json, tests/src/st40_test.cpp, tests/src/tests.h
also add empty frame(ANC_Count: 0) support
=> st40/tx: add interlaced support

doc/xdp.md, lib/src/dev/mt_af_xdp.c
Free all the mbufs remained in rx fill ring.
=> xdp: fix mempool leak

app/src/rxtx_app.c, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/pipeline/st20_pipeline_rx.h, lib/src/st2110/pipeline/st20_pipeline_tx.c, lib/src/st2110/pipeline/st20_pipeline_tx.h, lib/src/st2110/pipeline/st22_pipeline_rx.c, lib/src/st2110/pipeline/st22_pipeline_rx.h, lib/src/st2110/pipeline/st22_pipeline_tx.c, lib/src/st2110/pipeline/st22_pipeline_tx.h
also create stat for st20p for no external converter case.
=> st2110/pipeline: add stat for get frame call

lib/src/st2110/st_rx_video_session.c
rte_memcpy perform bad on this case
=> rx/video: use memcpy for copy payload to frame

lib/src/mt_main.h, lib/src/mt_ptp.c
improve the correct_delta to ~1us accuracy
=> ptp: add t2/t3 calibrate for VF

doc/xdp.md, include/mtl_api.h, lib/src/dev/mt_af_xdp.c, lib/src/mt_instance.c, lib/src/mt_mcast.c, lib/src/mt_ptp.c, lib/src/st2110/st_fmt.c, tests/script/backend_mix_json/dpdk_xdp.json, tests/script/backend_mix_json/xdp_dpdk.json, tests/script/native_af_xdp_json/loop.json
one dpdk port and one xdp port
test with:
./build/app/RxTxApp --config_file tests/script/backend_mix_json/dpdk_xdp.json
=> backend: fix mix device running

lib/src/st2110/st_header.h, lib/src/st2110/st_tx_audio_session.c, tests/script/audio_json/loop_128us_u32_96k.json, tests/src/st30_test.cpp, tests/src/tests.cpp, tests/src/tests.h
Also add `--audio_tx_pacing` option for gtest
=> st30/rl: add pad inflight support

lib/src/mt_log.h, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_timing_parser.c, lib/src/st2110/st_rx_timing_parser.h
also count tsdf every 200ms to follow the standard
=> rx_timing_parser/audio: add redundant support

lib/src/st2110/st_header.h, lib/src/st2110/st_rx_timing_parser.c, lib/src/st2110/st_tx_audio_session.c
test with:
numactl -C 28 ./sch_smi_emulate --sleep_ms 2 --work_us 150
=> audio/rl: force to tsc sync if warmup fail

.github/workflows/centos_build.yml, .github/workflows/ubuntu_build.yml, CHANGELOG.md, doc/usdt.md, lib/meson.build, lib/src/mt_ptp.c, lib/src/mt_usdt.h, tools/ebpf/Makefile, tools/ebpf/README.md
User Statically-Defined Tracing (USDT) probes bring the flexibility of kernel trace points to user-space applications.
=> usdt: introduce usdt support

tools/ebpf/lcore_monitor.bpf.c, tools/ebpf/lcore_monitor.c, tools/ebpf/lcore_monitor.h
hook on:
tracepoint:raw_syscalls:sys_enter
tracepoint:raw_syscalls:sys_exit
=> lcore_monitor: add syscall track

app/perf/p10le_to_rfc4175_422be10.c, app/perf/perf_dma.c, app/perf/perf_test.sh, app/perf/rfc4175_422be10_to_le.c, app/perf/rfc4175_422be10_to_le8.c, app/perf/rfc4175_422be10_to_p10le.c, app/perf/rfc4175_422be10_to_p8.c, app/perf/rfc4175_422be10_to_v210.c, app/perf/rfc4175_422be10_to_y210.c, app/perf/rfc4175_422be12_to_le.c, app/perf/rfc4175_422be12_to_p12le.c, app/perf/rfc4175_422le10_to_be.c, app/perf/v210_to_rfc4175_422be10.c, app/perf/y210_to_rfc4175_422be10.c, app/sample/sample_util.c, app/sample/sample_util.h, doc/convert.md, script/build_app.sh
usage:
./build/app/PerfRfc4175422be10ToP10Le --p_port 0000:af:01.0 --dma_port 0000:80:04.0 --perf_frames 120 --perf_fb_cnt 3 --log_level error
=> app/perf: add frames and fb_cnt options

README.md, doc/convert.md, include/st_convert_api.h, include/st_convert_internal.h, include/st_pipeline_api.h, lib/src/st2110/st_convert.c, lib/src/st2110/st_fmt.c, python/example/misc_util.py, python/example/rfc4175be10_convert_2way.py, python/example/st20p_rx.py, python/example/st20p_tx.py, python/example/st20p_tx_decode.py, python/example/st22p_rx.py, python/example/st22p_tx.py, python/swig/pymtl.i
experimental usage only, and no simd support.
Also move all DMA helper to internal usage.
=> convert: add 2 way support

.github/workflows/afxdp_build.yml, .github/workflows/centos_build.yml, .github/workflows/clang_build.yml, .github/workflows/codeql.yml, .github/workflows/ecosystem.yml, .github/workflows/ffmpeg_plugin.yml, .github/workflows/tools_build.yml, .github/workflows/ubuntu_build.yml, build.sh, include/st_api.h, lib/src/meson.build, lib/src/mt_main.h, lib/src/mt_pcap.c, lib/src/mt_pcap.h, lib/src/mt_platform.h, lib/src/mt_util.c, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_video_session.c, meson.build, meson_options.txt, patches/dpdk/23.11/0007-pcapng-add-user-timestamp-support.patch, tests/src/st20_test.cpp, tests/src/st22_test.cpp
also move pcap function to new file that can be used by others later.
=> pcap: add time stamp support

doc/usdt.md, lib/src/mt_usdt.h, lib/src/mt_usdt_provider.d, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c
also correct stat for redunant for st30/st40
=> usdt: add incomplete frame trace for st20

doc/usdt.md, kahawai.json, lib/src/mt_usdt.h, lib/src/mt_usdt_provider.d, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_video_session.c, plugins/st22_avcodec/README.md, python/README.md
The packets of each st22 codestream may vary
=> st22: force to no chain and tsc pacing

app/sample/ext_frame/rx_st20p_hdr_split_gpu_direct.c, app/src/app_base.h, app/src/args.c, app/src/legacy/tx_audio_app.c, app/src/tx_ancillary_app.c, app/src/tx_st30p_app.c, doc/experimental/header_split.md, include/st30_api.h, include/st30_pipeline_api.h, include/st40_api.h, lib/src/st2110/pipeline/st30_pipeline_tx.c, lib/src/st2110/st_header.h, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c, tests/src/st30p_test.cpp, tests/src/st40_test.cpp
ST30_TX_FLAG_DEDICATE_QUEUE and ST40_TX_FLAG_DEDICATE_QUEUE
=> st2110/tx: add dedicated queue support for st30 and st40

ecosystem/ffmpeg_plugin/4.4/0001-avdevice-add-mtl-in-out-dev-support.patch, ecosystem/ffmpeg_plugin/6.1/0001-avdevice-add-mtl-in-out-dev-support.patch, ecosystem/ffmpeg_plugin/README.md, ecosystem/ffmpeg_plugin/mtl_common.h, ecosystem/ffmpeg_plugin/mtl_st20p_tx.c, ecosystem/ffmpeg_plugin/mtl_st22p_rx.c, ecosystem/ffmpeg_plugin/mtl_st22p_tx.c, lib/src/st2110/pipeline/st22_pipeline_rx.c
For the case to use ffmpeg encoder/decoder.
=> ffmpeg_plugin: add st22 support

lib/src/st2110/st_tx_video_session.c
fix the error migration if the build timeout occurs occasionally
=> tx/video: clear cbs_build_timeout at every busy calculation

include/st_pipeline_api.h, lib/src/st2110/pipeline/st20_pipeline_rx.c
These were changes required for IMTL to support format detection in my rx/tx pipline fwd application
=> Format detection implemented into st20_pipline

app/src/app_base.h, app/src/args.c, app/src/legacy/tx_st22_app.c, app/src/legacy/tx_video_app.c, doc/run.md, lib/src/mt_main.h, lib/src/mt_sch.c
use args: "--bind_app_lcore" to bind the app thread to lcore
=> app/video: default not bind to lcore for tx

app/meson.build, app/sample/ext_frame/tx_video_split_sample.c, app/sample/meson.build, app/sample/rx_st20p_auto_detect_sample.c, app/sample/tx_st20_pipeline_sample.c, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/st_rx_video_session.c, tests/src/st20p_test.cpp
test with:
./build/app/RxVideoAutoDetectSample --rx_dump
./build/app/RxVideoAutoDetectSample --rx_dump --pipeline_fmt YUV422RFC4175PG2BE10
=> st20p/rx: add auto detect support for non-ext-frame mode

app/src/app_base.h, app/src/args.c, app/src/legacy/rx_video_app.c, app/src/rx_st20p_app.c, doc/run.md, include/mtl_api.h, include/st20_api.h, include/st_pipeline_api.h, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_sch.c, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/st_rx_video_session.c, tools/ebpf/et.h, tools/ebpf/lcore_monitor.h, tools/ebpf/udp_monitor.h
./build/app/RxTxApp --config_file tests/script/loop_json/1080p59_1v.json --not_bind_numa
=> lcore: not check socket id if MTL_FLAG_BIND_NUMA not enabled

rdma/mt_rdma.h, rdma/mt_rdma_rx.c, rdma/mt_rdma_tx.c
Replace ready msg, rx side can know the write operation is done. This reduces the rtt/2 notify latency.
=> rdma: use rdma_write_with_imm

app/sample/ext_frame/rx_st20p_hdr_split_gpu_direct.c, app/sample/rx_st20_pipeline_sample.c, app/sample/rx_st20p_auto_detect_sample.c, app/sample/rx_st20p_timing_parser_sample.c, app/sample/rx_st22_pipeline_sample.c, app/sample/rx_st30_pipeline_sample.c, app/sample/sample_util.c, app/sample/sample_util.h, app/sample/tx_st20_pipeline_sample.c, app/sample/tx_st22_pipeline_sample.c, app/sample/tx_st30_pipeline_sample.c, lib/src/mt_dma.c
Increase the addr instead of udp port for multi sessions
=> app/sample: add multi_inc_addr option

lib/src/mt_admin.c, lib/src/mt_main.c, lib/src/mt_main.h, lib/src/mt_sch.c, lib/src/mt_sch.h, lib/src/mt_tap.c, lib/src/st2110/st_rx_video_session.c
Sessions can create a sch on any socket by mt_sch_get_by_socket.
=> sch: add socket support

app/src/app_base.h, app/src/args.c, app/src/legacy/rx_video_app.c, app/src/legacy/tx_video_app.c, app/src/rx_st20p_app.c, app/src/rx_st22p_app.c, app/src/rxtx_app.c, app/src/tx_st20p_app.c, app/src/tx_st22p_app.c, include/st20_api.h, include/st_pipeline_api.h, lib/src/mt_admin.c, lib/src/mt_main.h, lib/src/mt_sch.c, lib/src/mt_sch.h, lib/src/mt_util.c, lib/src/mt_util.h, lib/src/st2110/pipeline/st20_pipeline_rx.c, lib/src/st2110/pipeline/st20_pipeline_rx.h, lib/src/st2110/pipeline/st20_pipeline_tx.c, lib/src/st2110/pipeline/st20_pipeline_tx.h, lib/src/st2110/pipeline/st22_pipeline_rx.c, lib/src/st2110/pipeline/st22_pipeline_rx.h, lib/src/st2110/pipeline/st22_pipeline_tx.c, lib/src/st2110/pipeline/st22_pipeline_tx.h, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_video_session.c, lib/src/st2110/st_tx_video_session.c, plugins/sample/st22_plugin_sample.c
test with:
./build/app/RxTxApp --config_file tests/script/loop_json/st20p_1v_planar10.json --force_rx_video_numa 0
./build/app/RxTxApp --config_file tests/script/loop_json/st20p_1v_planar10.json --force_tx_video_numa 0
=> st2110/video: add force numa option

lib/src/datapath/mt_dp_socket.c, lib/src/datapath/mt_shared_queue.c, lib/src/dev/mt_af_xdp.c, lib/src/dev/mt_dev.c, lib/src/mt_arp.c, lib/src/mt_flow.c, lib/src/mt_main.h, lib/src/mt_mcast.c, lib/src/mt_socket.c, lib/src/mt_socket.h, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_rx_video_session.c, tests/script/native_af_xdp_json/mcast.json
also add mcast support for af_pkt
=> mcast: move socket based join to socket module

CHANGELOG.md, app/src/app_base.h, app/src/args.c, app/src/legacy/rx_audio_app.c, app/src/legacy/tx_audio_app.c, app/src/rx_st30p_app.c, app/src/rxtx_app.c, app/src/tx_st30p_app.c, include/st30_api.h, include/st30_pipeline_api.h, lib/src/st2110/pipeline/st30_pipeline_rx.c, lib/src/st2110/pipeline/st30_pipeline_rx.h, lib/src/st2110/pipeline/st30_pipeline_tx.c, lib/src/st2110/pipeline/st30_pipeline_tx.h, lib/src/st2110/st_header.h, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_rx_audio_session.c, lib/src/st2110/st_tx_ancillary_session.c, lib/src/st2110/st_tx_audio_session.c
test with:
./build/app/RxTxApp --config_file tests/script/audio_json/st30p_loop.json --force_tx_audio_numa 0 
and
./build/app/RxTxApp --config_file tests/script/audio_json/st30p_loop.json --force_rx_audio_numa 0
=> audio: add numa option support

.github/path_filters.yml, lib/src/dev/mt_af_xdp.c, lib/src/mt_util.c, manager/meson.build, manager/mtl_interface.hpp, manager/mtl_manager.cpp
[2024-06-25 10:12:24] [INFO] MTL Manager version: 24.6.0.REL Tue Jun 25 10:08:21 2024 4856224b-dirty clang-14.0.0-1ubuntu1
=> manager: add mtlm_version

lib/src/mt_ptp.c, lib/src/st2110/st_rx_video_session.c
(cherry picked from commit d2f8ffe5da5b30a45708cf079b84760e976e61e7)
=> ptp: fix panic if run rx timing with pf

lib/src/mt_dma.c, tests/src/dma_test.cpp
also add a test case for this issue
=> dma: fix map error if start is the end of previous map

lib/src/mt_util.c
Enhance the memory utilization in the DPDK mempool creation function by adjusting the number
of elements to the nearest higher power
of two minus one.
=> Optimize memory pool size in DPDK function

.github/workflows/coverity.yml, README.md
Changelog:
* integrate coverity project
* add coverity daily scheduled scans to Github actions
*  add coverity status badge  to readme.md
=> Z lukas/add coverity scan

.github/workflows/ffmpeg_plugin.yml, ecosystem/ffmpeg_plugin/7.0/0001-avdevice-add-mtl-in-out-dev-support.patch, ecosystem/ffmpeg_plugin/README.md, ecosystem/ffmpeg_plugin/build_ffmpeg_plugin.sh, ecosystem/ffmpeg_plugin/mtl_common.c, ecosystem/ffmpeg_plugin/mtl_common.h, ecosystem/ffmpeg_plugin/mtl_st20p_rx.c, ecosystem/ffmpeg_plugin/mtl_st22p_rx.c, ecosystem/ffmpeg_plugin/mtl_st30p_rx.c
Modify patches/plugins to support ffmpeg 7.0
=> ffmpeg 7.0 plugins

.github/workflows/coverity.yml, .github/workflows/trivy.yml, docker/ubuntu.dockerfile
* trivy scan added to github actions
=> Enable Trivy scan 

.gitignore
Exclude .patch files from being ignored in
the patch and ecosystem directories
=> Add Exemptions for .patch Files in .gitignore

.github/workflows/trivy.yml
ADD:
* alligs pipeline steps the same way as it is in Media-Communication-Mesh repo
=> Allign trivy workflow to MCM pipeline

app/src/app_base.h, app/src/parse_json.c, app/src/rx_st20p_app.c
Add support for st20p RxTxApp video saving using
alraedy existing video url json parsing.
=> Add: support for saving video to file in st20p

.github/workflows/codeql.yml
FIX: Update codeql.yml to fix consistent error:
- Set explicit ubuntu version to 22.04
- Install clang and llvm by default
=> FIX: Update codeql.yml to fix consistent error

.github/workflows/ecosystem.yml
Update ecosystem.yml by adding the missing meson build  dependencies.
=> FIX: Update ecosystem.yml

.github/workflows/coverity.yml
* move coveirty scan from main to rc branch
=> update coverity branch

.github/workflows/trivy.yml
extend trivy scan to release branch:
* add schedule to run every day at 11 p.m on release branch
=> run trivy on release branch

.github/workflows/validation-tests.yml
Add: CiCd Validation Tests Automation.
This include manual workflow that can be triggered by validation team to run any existing tests.
=> Add: CiCd Validation Tests Automation

.github/workflows/gtest-bare-metal.yml
Update and rename `gtest-bare-metal` file:
- Rename `ubuntu_build_with_gtest.yml` to `gtest-bare-metal.yml` to reflect the workflow naming convention
- Allow branch choosing for workflow run,
=> Refactor: Update and rename ubuntu_build_with_gtest.yml

format-coding.sh
FIX:
* allign format-coding script with super-linter
=> allign format-coding.sh with super linter

script/nicctl.sh
=> Add: list VFs by device address in nicctl.sh

.github/actions/dpdk/action.yml, .github/workflows/afxdp_build.yml, .github/workflows/base_build.yml, .github/workflows/centos_build.yml, .github/workflows/ecosystem.yml, .github/workflows/ffmpeg_plugin.yml
FIX:
* move  duplicated DPDK install steps from each build workflow into standalone to action
* replace DPDK install steps in workflows with action
=> FIX:  duplicated dpdk install step

.github/workflows/gtest-bare-metal.yml
Adjust directory tree ownership on gtest-bare-metal.yml
=> Fix: Adjust directory tree ownership on gtest-bare-metal.yml

.github/path_filters.yml
Fix
* update gtest job trigger configuration
=> Ci: Fix gtest filter

.github/path_filters.yml, .github/workflows/gtest-bare-metal.yml
Workaround to fix CI/CD UT failure
=> Ci: Fix CICD Unit Tests fails

ecosystem/gstreamer_plugin/gst_mtl_st40_rx.c, include/st40_api.h, lib/src/st2110/st_rx_ancillary_session.c, lib/src/st2110/st_tx_ancillary_session.c, tests/tools/RxTxApp/src/rx_ancillary_app.c, tests/tools/RxTxApp/src/tx_ancillary_app.c, tests/unittest/st40_test.cpp
Added option to support conversion from big to little endian in st40 RTP header.
=> Add support of endianness for st40_rfc8331_rtp_hdr

doc/e810.md, include/st20_api.h, include/st_pipeline_api.h, lib/src/mt_main.h, lib/src/mt_util.c, lib/src/mt_util.h, lib/src/st2110/pipeline/st20_pipeline_tx.c, lib/src/st2110/st_tx_audio_session.c, lib/src/st2110/st_tx_video_session.c, patches/ice_drv/2.2.8/0001-vf-support-kahawai-runtime-rl-queue.patch, patches/ice_drv/2.2.8/0002-ice-set-ICE_SCHED_DFLT_BURST_SIZE-to-2048.patch, patches/ice_drv/2.2.8/0003-allow-VIRTCHNL_VF_LARGE_NUM_QPAIRS-for-ICE_LUT_VSI.patch, patches/ice_drv/2.2.8/0004-version-update-to-Kahawai_2.2.8.patch, tests/tools/RxTxApp/src/app_base.h, tests/tools/RxTxApp/src/args.c, tests/tools/RxTxApp/src/legacy/tx_video_app.c, tests/tools/RxTxApp/src/tx_st20p_app.c, versions.env
This Pull request is based on and replace https://github.com/OpenVisualCloud/Media-Transport-Library/pull/1153
1. Fix handling case where RL is lower then expected
2. Update ice driver to version 2.2.8
=> Fix: handling case where RL is lower then expected

app/sample/ext_frame/rx_st20_pipeline_dyn_ext_frame_sample.c
* Added iova parameter
* Added warning that yuv420 format for external frame is not supported
=> Fix: update RxSt20pDynExtFrameSample to allow use of ext_frame
